// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quota.sql

package sqlcgen

import (
	"context"
)

const getQuotaIdempotency = `-- name: GetQuotaIdempotency :one
SELECT request_hash, response_json
FROM agent_idempotency
WHERE tenant_id = cast(?1 AS text)
  AND principal_kind = 'system'
  AND principal_id = 'quota'
  AND operation = cast(?2 AS text)
  AND idempotency_key = cast(?3 AS text)
  AND expires_at_ns > cast(?4 AS integer)
`

type GetQuotaIdempotencyParams struct {
	TenantID       string
	Operation      string
	IdempotencyKey string
	NowNs          int64
}

type GetQuotaIdempotencyRow struct {
	RequestHash  []byte
	ResponseJson string
}

func (q *Queries) GetQuotaIdempotency(ctx context.Context, arg GetQuotaIdempotencyParams) (GetQuotaIdempotencyRow, error) {
	row := q.db.QueryRowContext(ctx, getQuotaIdempotency,
		arg.TenantID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.NowNs,
	)
	var i GetQuotaIdempotencyRow
	err := row.Scan(&i.RequestHash, &i.ResponseJson)
	return i, err
}

const incrementQuotaWindow = `-- name: IncrementQuotaWindow :one
UPDATE quota_windows
SET used = used + cast(?1 AS integer)
WHERE tenant_id = cast(?2 AS text)
  AND action = cast(?3 AS text)
  AND window_started_at_ns = cast(?4 AS integer)
  AND used <= cast(?5 AS integer) - cast(?1 AS integer)
RETURNING used
`

type IncrementQuotaWindowParams struct {
	Units             int64
	TenantID          string
	Action            string
	WindowStartedAtNs int64
	QuotaLimit        int64
}

func (q *Queries) IncrementQuotaWindow(ctx context.Context, arg IncrementQuotaWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementQuotaWindow,
		arg.Units,
		arg.TenantID,
		arg.Action,
		arg.WindowStartedAtNs,
		arg.QuotaLimit,
	)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const insertQuotaIdempotency = `-- name: InsertQuotaIdempotency :exec
INSERT INTO agent_idempotency (
    tenant_id, principal_kind, principal_id, operation, idempotency_key,
    request_hash, response_json, created_at_ns, expires_at_ns
)
VALUES (
    cast(?1 AS text),
    'system',
    'quota',
    cast(?2 AS text),
    cast(?3 AS text),
    ?4,
    cast(?5 AS text),
    cast(?6 AS integer),
    cast(?7 AS integer)
)
`

type InsertQuotaIdempotencyParams struct {
	TenantID       string
	Operation      string
	IdempotencyKey string
	RequestHash    []byte
	ResponseJson   string
	CreatedAtNs    int64
	ExpiresAtNs    int64
}

func (q *Queries) InsertQuotaIdempotency(ctx context.Context, arg InsertQuotaIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, insertQuotaIdempotency,
		arg.TenantID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResponseJson,
		arg.CreatedAtNs,
		arg.ExpiresAtNs,
	)
	return err
}

const insertQuotaWindow = `-- name: InsertQuotaWindow :one
INSERT INTO quota_windows (tenant_id, action, window_started_at_ns, used)
SELECT
    cast(?1 AS text),
    cast(?2 AS text),
    cast(?3 AS integer),
    cast(?4 AS integer)
WHERE cast(?4 AS integer) <= cast(?5 AS integer)
ON CONFLICT (tenant_id, action, window_started_at_ns) DO NOTHING
RETURNING used
`

type InsertQuotaWindowParams struct {
	TenantID          string
	Action            string
	WindowStartedAtNs int64
	Units             int64
	QuotaLimit        int64
}

func (q *Queries) InsertQuotaWindow(ctx context.Context, arg InsertQuotaWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertQuotaWindow,
		arg.TenantID,
		arg.Action,
		arg.WindowStartedAtNs,
		arg.Units,
		arg.QuotaLimit,
	)
	var used int64
	err := row.Scan(&used)
	return used, err
}
