// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding.sql

package sqlcgen

import (
	"context"
	"time"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id, created_at)
VALUES (?, ?, ?)
`

type AssignUserRoleParams struct {
	UserID    string
	RoleID    string
	CreatedAt time.Time
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignUserRole, arg.UserID, arg.RoleID, arg.CreatedAt)
	return err
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*)
FROM user_roles ur
         INNER JOIN roles r ON ur.role_id = r.role_id
WHERE r.role_name = 'admin'
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_id, email, password, verified, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	UserID    string
	Email     string
	Password  string
	Verified  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Password,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getAdminRoleID = `-- name: GetAdminRoleID :one
SELECT role_id
FROM roles
WHERE role_name = 'admin'
`

func (q *Queries) GetAdminRoleID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAdminRoleID)
	var role_id string
	err := row.Scan(&role_id)
	return role_id, err
}
