// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountExpiredCredentials = `-- name: AccountExpiredCredentials :many
UPDATE agent_credentials
SET expired_accounted_at_ns = $1::bigint
WHERE tenant_id = $2::text
  AND agent_id = $3::text
  AND revoked_at_ns IS NULL
  AND expired_accounted_at_ns IS NULL
  AND expires_at_ns IS NOT NULL
  AND expires_at_ns <= $1::bigint
RETURNING credential_id
`

type AccountExpiredCredentialsParams struct {
	AccountedAtNs int64
	TenantID      string
	AgentID       string
}

func (q *Queries) AccountExpiredCredentials(ctx context.Context, arg AccountExpiredCredentialsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, accountExpiredCredentials, arg.AccountedAtNs, arg.TenantID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var credential_id string
		if err := rows.Scan(&credential_id); err != nil {
			return nil, err
		}
		items = append(items, credential_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveCredentials = `-- name: CountActiveCredentials :one
SELECT count(*)
FROM agent_credentials
WHERE tenant_id = $1::text
  AND agent_id = $2::text
  AND revoked_at_ns IS NULL
  AND expired_accounted_at_ns IS NULL
  AND (expires_at_ns IS NULL OR expires_at_ns > $3::bigint)
`

type CountActiveCredentialsParams struct {
	TenantID string
	AgentID  string
	NowNs    int64
}

func (q *Queries) CountActiveCredentials(ctx context.Context, arg CountActiveCredentialsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCredentials, arg.TenantID, arg.AgentID, arg.NowNs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgents = `-- name: CountAgents :one
SELECT count(*)
FROM agents
WHERE tenant_id = $1::text
  AND ($2::text = '' OR left(agent_name, char_length($2::text)) = $2::text)
`

type CountAgentsParams struct {
	TenantID   string
	NamePrefix string
}

func (q *Queries) CountAgents(ctx context.Context, arg CountAgentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgents, arg.TenantID, arg.NamePrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (
    agent_id, tenant_id, agent_name, status, auth_version,
    created_by_kind, created_by_id, created_at_ns, updated_at_ns
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAgentParams struct {
	AgentID       string
	TenantID      string
	AgentName     string
	Status        int16
	AuthVersion   int64
	CreatedByKind string
	CreatedByID   string
	CreatedAtNs   int64
	UpdatedAtNs   int64
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.Exec(ctx, createAgent,
		arg.AgentID,
		arg.TenantID,
		arg.AgentName,
		arg.Status,
		arg.AuthVersion,
		arg.CreatedByKind,
		arg.CreatedByID,
		arg.CreatedAtNs,
		arg.UpdatedAtNs,
	)
	return err
}

const createAgentPrincipal = `-- name: CreateAgentPrincipal :exec
INSERT INTO security_principals (
    tenant_id, principal_kind, principal_id, status, roles_json,
    auth_version, updated_at_ns
)
VALUES ($1, 'agent', $2, 'active', '["agent"]'::jsonb, $3, $4)
`

type CreateAgentPrincipalParams struct {
	TenantID    string
	PrincipalID string
	AuthVersion int64
	UpdatedAtNs int64
}

func (q *Queries) CreateAgentPrincipal(ctx context.Context, arg CreateAgentPrincipalParams) error {
	_, err := q.db.Exec(ctx, createAgentPrincipal,
		arg.TenantID,
		arg.PrincipalID,
		arg.AuthVersion,
		arg.UpdatedAtNs,
	)
	return err
}

const createAgentResourceUsage = `-- name: CreateAgentResourceUsage :exec
INSERT INTO agent_resource_usage (
    tenant_id, agent_id, pending_direct_count, pending_direct_bytes,
    subscription_count, active_credential_count, updated_at_ns
)
VALUES ($1, $2, 0, 0, 0, 0, $3)
`

type CreateAgentResourceUsageParams struct {
	TenantID    string
	AgentID     string
	UpdatedAtNs int64
}

func (q *Queries) CreateAgentResourceUsage(ctx context.Context, arg CreateAgentResourceUsageParams) error {
	_, err := q.db.Exec(ctx, createAgentResourceUsage, arg.TenantID, arg.AgentID, arg.UpdatedAtNs)
	return err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO agent_credentials (
    credential_id, tenant_id, agent_id, credential_name, credential_prefix,
    secret_hash, created_at_ns, expires_at_ns
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateCredentialParams struct {
	CredentialID     string
	TenantID         string
	AgentID          string
	CredentialName   string
	CredentialPrefix string
	SecretHash       []byte
	CreatedAtNs      int64
	ExpiresAtNs      pgtype.Int8
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.CredentialID,
		arg.TenantID,
		arg.AgentID,
		arg.CredentialName,
		arg.CredentialPrefix,
		arg.SecretHash,
		arg.CreatedAtNs,
		arg.ExpiresAtNs,
	)
	return err
}

const decrementActiveCredentialUsage = `-- name: DecrementActiveCredentialUsage :execrows
UPDATE agent_resource_usage
SET active_credential_count = active_credential_count - 1,
    updated_at_ns = $1::bigint
WHERE tenant_id = $2::text AND agent_id = $3::text
  AND active_credential_count > 0
`

type DecrementActiveCredentialUsageParams struct {
	UpdatedAtNs int64
	TenantID    string
	AgentID     string
}

func (q *Queries) DecrementActiveCredentialUsage(ctx context.Context, arg DecrementActiveCredentialUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementActiveCredentialUsage, arg.UpdatedAtNs, arg.TenantID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteResourceGrant = `-- name: DeleteResourceGrant :execrows
DELETE FROM agent_resource_grants
WHERE tenant_id = $1::text AND grant_id = $2::text
`

type DeleteResourceGrantParams struct {
	TenantID string
	GrantID  string
}

func (q *Queries) DeleteResourceGrant(ctx context.Context, arg DeleteResourceGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResourceGrant, arg.TenantID, arg.GrantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgent = `-- name: GetAgent :one
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = $1 AND agent_id = $2
`

type GetAgentParams struct {
	TenantID string
	AgentID  string
}

type GetAgentRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int16
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs pgtype.Int8
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.TenantID, arg.AgentID)
	var i GetAgentRow
	err := row.Scan(
		&i.AgentID,
		&i.TenantID,
		&i.AgentName,
		&i.Status,
		&i.AuthVersion,
		&i.CreatedAtNs,
		&i.UpdatedAtNs,
		&i.DisabledAtNs,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = $1 AND agent_name = $2
`

type GetAgentByNameParams struct {
	TenantID  string
	AgentName string
}

type GetAgentByNameRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int16
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs pgtype.Int8
}

func (q *Queries) GetAgentByName(ctx context.Context, arg GetAgentByNameParams) (GetAgentByNameRow, error) {
	row := q.db.QueryRow(ctx, getAgentByName, arg.TenantID, arg.AgentName)
	var i GetAgentByNameRow
	err := row.Scan(
		&i.AgentID,
		&i.TenantID,
		&i.AgentName,
		&i.Status,
		&i.AuthVersion,
		&i.CreatedAtNs,
		&i.UpdatedAtNs,
		&i.DisabledAtNs,
	)
	return i, err
}

const getAgentCredentialCapacity = `-- name: GetAgentCredentialCapacity :one
SELECT u.active_credential_count, q.max_credentials_per_agent
FROM agent_resource_usage u
JOIN tenant_quotas q ON q.tenant_id = u.tenant_id
WHERE u.tenant_id = $1::text AND u.agent_id = $2::text
FOR UPDATE OF u
`

type GetAgentCredentialCapacityParams struct {
	TenantID string
	AgentID  string
}

type GetAgentCredentialCapacityRow struct {
	ActiveCredentialCount  int64
	MaxCredentialsPerAgent int64
}

func (q *Queries) GetAgentCredentialCapacity(ctx context.Context, arg GetAgentCredentialCapacityParams) (GetAgentCredentialCapacityRow, error) {
	row := q.db.QueryRow(ctx, getAgentCredentialCapacity, arg.TenantID, arg.AgentID)
	var i GetAgentCredentialCapacityRow
	err := row.Scan(&i.ActiveCredentialCount, &i.MaxCredentialsPerAgent)
	return i, err
}

const getAgentPrincipal = `-- name: GetAgentPrincipal :one
SELECT tenant_id, principal_id, status, auth_version
FROM security_principals
WHERE tenant_id = $1 AND principal_kind = 'agent' AND principal_id = $2
`

type GetAgentPrincipalParams struct {
	TenantID    string
	PrincipalID string
}

type GetAgentPrincipalRow struct {
	TenantID    string
	PrincipalID string
	Status      string
	AuthVersion int64
}

func (q *Queries) GetAgentPrincipal(ctx context.Context, arg GetAgentPrincipalParams) (GetAgentPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getAgentPrincipal, arg.TenantID, arg.PrincipalID)
	var i GetAgentPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.PrincipalID,
		&i.Status,
		&i.AuthVersion,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT credential_id, tenant_id, agent_id, credential_name, credential_prefix,
       secret_hash, created_at_ns, expires_at_ns, expired_accounted_at_ns,
       revoked_at_ns, last_used_at_ns
FROM agent_credentials
WHERE credential_id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, credentialID string) (AgentCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, credentialID)
	var i AgentCredential
	err := row.Scan(
		&i.CredentialID,
		&i.TenantID,
		&i.AgentID,
		&i.CredentialName,
		&i.CredentialPrefix,
		&i.SecretHash,
		&i.CreatedAtNs,
		&i.ExpiresAtNs,
		&i.ExpiredAccountedAtNs,
		&i.RevokedAtNs,
		&i.LastUsedAtNs,
	)
	return i, err
}

const getCredentialByPrefix = `-- name: GetCredentialByPrefix :one
SELECT credential_id, tenant_id, agent_id, credential_name, credential_prefix,
       secret_hash, created_at_ns, expires_at_ns, expired_accounted_at_ns,
       revoked_at_ns, last_used_at_ns
FROM agent_credentials
WHERE credential_prefix = $1
`

func (q *Queries) GetCredentialByPrefix(ctx context.Context, credentialPrefix string) (AgentCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByPrefix, credentialPrefix)
	var i AgentCredential
	err := row.Scan(
		&i.CredentialID,
		&i.TenantID,
		&i.AgentID,
		&i.CredentialName,
		&i.CredentialPrefix,
		&i.SecretHash,
		&i.CreatedAtNs,
		&i.ExpiresAtNs,
		&i.ExpiredAccountedAtNs,
		&i.RevokedAtNs,
		&i.LastUsedAtNs,
	)
	return i, err
}

const getMutationRateLimit = `-- name: GetMutationRateLimit :one
SELECT (CASE WHEN $1::text = 'topic.publish' THEN publish_per_second ELSE send_per_second END)::bigint
FROM tenant_quotas
WHERE tenant_id = $2::text
`

type GetMutationRateLimitParams struct {
	Action   string
	TenantID string
}

func (q *Queries) GetMutationRateLimit(ctx context.Context, arg GetMutationRateLimitParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMutationRateLimit, arg.Action, arg.TenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPolicyIdempotency = `-- name: GetPolicyIdempotency :one
SELECT request_hash, response_json
FROM agent_idempotency
WHERE tenant_id = $1::text
  AND principal_kind = $2::text
  AND principal_id = $3::text
  AND operation = $4::text
  AND idempotency_key = $5::text
  AND expires_at_ns > $6::bigint
`

type GetPolicyIdempotencyParams struct {
	TenantID       string
	PrincipalKind  string
	PrincipalID    string
	Operation      string
	IdempotencyKey string
	NowNs          int64
}

type GetPolicyIdempotencyRow struct {
	RequestHash  []byte
	ResponseJson []byte
}

func (q *Queries) GetPolicyIdempotency(ctx context.Context, arg GetPolicyIdempotencyParams) (GetPolicyIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getPolicyIdempotency,
		arg.TenantID,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.NowNs,
	)
	var i GetPolicyIdempotencyRow
	err := row.Scan(&i.RequestHash, &i.ResponseJson)
	return i, err
}

const getResourceGrant = `-- name: GetResourceGrant :one
SELECT grant_id, tenant_id, subject_kind, subject_id,
       resource_kind, resource_id, action, created_at_ns
FROM agent_resource_grants
WHERE tenant_id = $1::text AND grant_id = $2::text
`

type GetResourceGrantParams struct {
	TenantID string
	GrantID  string
}

func (q *Queries) GetResourceGrant(ctx context.Context, arg GetResourceGrantParams) (AgentResourceGrant, error) {
	row := q.db.QueryRow(ctx, getResourceGrant, arg.TenantID, arg.GrantID)
	var i AgentResourceGrant
	err := row.Scan(
		&i.GrantID,
		&i.TenantID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.Action,
		&i.CreatedAtNs,
	)
	return i, err
}

const getTenantAgentCapacity = `-- name: GetTenantAgentCapacity :one
SELECT u.agent_count, q.max_agents
FROM tenant_resource_usage u
JOIN tenant_quotas q ON q.tenant_id = u.tenant_id
WHERE u.tenant_id = $1
FOR UPDATE OF u
`

type GetTenantAgentCapacityRow struct {
	AgentCount int64
	MaxAgents  int64
}

func (q *Queries) GetTenantAgentCapacity(ctx context.Context, tenantID string) (GetTenantAgentCapacityRow, error) {
	row := q.db.QueryRow(ctx, getTenantAgentCapacity, tenantID)
	var i GetTenantAgentCapacityRow
	err := row.Scan(&i.AgentCount, &i.MaxAgents)
	return i, err
}

const hasLegacyPolicyPermission = `-- name: HasLegacyPolicyPermission :one
WITH effective_roles AS (
    SELECT ur.role_id FROM user_roles ur WHERE ur.user_id = $2::text
    UNION
    SELECT tr.role_id
    FROM user_teams ut
    JOIN teams t ON t.team_id = ut.team_id
    JOIN team_roles tr ON tr.team_id = t.team_id
    WHERE ut.user_id = $2::text AND t.org_id = $3::text AND t.is_active = TRUE
)
SELECT EXISTS (
    SELECT 1
    FROM users u
    JOIN organizations o ON o.org_id = u.org_id AND o.is_active = TRUE
    JOIN effective_roles er ON TRUE
    JOIN roles r ON r.role_id = er.role_id
    LEFT JOIN queue_properties q ON q.queue_id = $1::text AND q.tenant_id = u.org_id
    LEFT JOIN queue_permissions qp ON qp.queue_id = q.queue_id AND qp.role_id = r.role_id
    WHERE u.user_id = $2::text
      AND u.org_id = $3::text
      AND u.status = 'active'
      AND (
        r.role_name = 'admin'
        OR (
          $4::text = 'queue' AND q.queue_id IS NOT NULL
          AND CASE $5::text
            WHEN 'queue.send' THEN coalesce(qp.can_send, FALSE)
            WHEN 'queue.receive' THEN coalesce(qp.can_receive, FALSE)
            WHEN 'queue.read' THEN coalesce(qp.can_receive, FALSE)
            WHEN 'queue.ack' THEN coalesce(qp.can_delete, FALSE)
            WHEN 'queue.purge' THEN coalesce(qp.can_purge, FALSE)
            WHEN 'queue.delete' THEN coalesce(qp.can_delete, FALSE)
            ELSE FALSE
          END
        )
      )
)
`

type HasLegacyPolicyPermissionParams struct {
	ResourceID   string
	SubjectID    string
	TenantID     string
	ResourceKind string
	Action       string
}

func (q *Queries) HasLegacyPolicyPermission(ctx context.Context, arg HasLegacyPolicyPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLegacyPolicyPermission,
		arg.ResourceID,
		arg.SubjectID,
		arg.TenantID,
		arg.ResourceKind,
		arg.Action,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasPolicyGrant = `-- name: HasPolicyGrant :one
SELECT EXISTS (
    SELECT 1
    FROM agent_resource_grants g
    JOIN security_principals p
      ON p.tenant_id = g.tenant_id
     AND p.principal_kind = g.subject_kind
     AND p.principal_id = g.subject_id
     AND p.status = 'active'
    WHERE g.tenant_id = $1::text
      AND g.subject_kind = $2::text
      AND g.subject_id = $3::text
      AND g.resource_kind = $4::text
      AND g.resource_id = $5::text
      AND g.action = $6::text
)
`

type HasPolicyGrantParams struct {
	TenantID     string
	SubjectKind  string
	SubjectID    string
	ResourceKind string
	ResourceID   string
	Action       string
}

func (q *Queries) HasPolicyGrant(ctx context.Context, arg HasPolicyGrantParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPolicyGrant,
		arg.TenantID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Action,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasResourceGrant = `-- name: HasResourceGrant :one
SELECT EXISTS (
    SELECT 1
    FROM agent_resource_grants
    WHERE tenant_id = $1::text
      AND subject_kind = $2::text
      AND subject_id = $3::text
      AND resource_kind = $4::text
      AND resource_id = $5::text
      AND action = $6::text
)
`

type HasResourceGrantParams struct {
	TenantID     string
	SubjectKind  string
	SubjectID    string
	ResourceKind string
	ResourceID   string
	Action       string
}

func (q *Queries) HasResourceGrant(ctx context.Context, arg HasResourceGrantParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasResourceGrant,
		arg.TenantID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Action,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementActiveCredentialUsage = `-- name: IncrementActiveCredentialUsage :execrows
UPDATE agent_resource_usage
SET active_credential_count = active_credential_count + 1,
    updated_at_ns = $1::bigint
WHERE tenant_id = $2::text
  AND agent_id = $3::text
  AND active_credential_count < $4::bigint
`

type IncrementActiveCredentialUsageParams struct {
	UpdatedAtNs     int64
	TenantID        string
	AgentID         string
	CredentialLimit int64
}

func (q *Queries) IncrementActiveCredentialUsage(ctx context.Context, arg IncrementActiveCredentialUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementActiveCredentialUsage,
		arg.UpdatedAtNs,
		arg.TenantID,
		arg.AgentID,
		arg.CredentialLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementMutationQuotaWindow = `-- name: IncrementMutationQuotaWindow :one
UPDATE quota_windows
SET used = used + $1::bigint
WHERE tenant_id = $2::text
  AND action = $3::text
  AND window_started_at_ns = $4::bigint
  AND used <= $5::bigint - $1::bigint
RETURNING used
`

type IncrementMutationQuotaWindowParams struct {
	Units             int64
	TenantID          string
	Action            string
	WindowStartedAtNs int64
	QuotaLimit        int64
}

func (q *Queries) IncrementMutationQuotaWindow(ctx context.Context, arg IncrementMutationQuotaWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementMutationQuotaWindow,
		arg.Units,
		arg.TenantID,
		arg.Action,
		arg.WindowStartedAtNs,
		arg.QuotaLimit,
	)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const incrementTenantAgentUsage = `-- name: IncrementTenantAgentUsage :execrows
UPDATE tenant_resource_usage
SET agent_count = agent_count + 1, updated_at_ns = $1::bigint
WHERE tenant_id = $2::text
`

type IncrementTenantAgentUsageParams struct {
	UpdatedAtNs int64
	TenantID    string
}

func (q *Queries) IncrementTenantAgentUsage(ctx context.Context, arg IncrementTenantAgentUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementTenantAgentUsage, arg.UpdatedAtNs, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAgentAuditEvent = `-- name: InsertAgentAuditEvent :exec
INSERT INTO security_audit_events (
    audit_id, tenant_id, principal_kind, principal_id, action,
    resource_kind, resource_id, outcome, request_id, reason,
    source_ip, user_agent, metadata_json, created_at_ns
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertAgentAuditEventParams struct {
	AuditID       string
	TenantID      string
	PrincipalKind string
	PrincipalID   string
	Action        string
	ResourceKind  string
	ResourceID    string
	Outcome       string
	RequestID     string
	Reason        string
	SourceIp      string
	UserAgent     string
	MetadataJson  []byte
	CreatedAtNs   int64
}

func (q *Queries) InsertAgentAuditEvent(ctx context.Context, arg InsertAgentAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAgentAuditEvent,
		arg.AuditID,
		arg.TenantID,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.Action,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Outcome,
		arg.RequestID,
		arg.Reason,
		arg.SourceIp,
		arg.UserAgent,
		arg.MetadataJson,
		arg.CreatedAtNs,
	)
	return err
}

const insertMutationQuotaWindow = `-- name: InsertMutationQuotaWindow :one
INSERT INTO quota_windows (tenant_id, action, window_started_at_ns, used)
SELECT $1::text, $2::text,
       $3::bigint, $4::bigint
WHERE $4::bigint <= $5::bigint
ON CONFLICT (tenant_id, action, window_started_at_ns) DO NOTHING
RETURNING used
`

type InsertMutationQuotaWindowParams struct {
	TenantID          string
	Action            string
	WindowStartedAtNs int64
	Units             int64
	QuotaLimit        int64
}

func (q *Queries) InsertMutationQuotaWindow(ctx context.Context, arg InsertMutationQuotaWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMutationQuotaWindow,
		arg.TenantID,
		arg.Action,
		arg.WindowStartedAtNs,
		arg.Units,
		arg.QuotaLimit,
	)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const insertPolicyIdempotency = `-- name: InsertPolicyIdempotency :exec
INSERT INTO agent_idempotency (
    tenant_id, principal_kind, principal_id, operation, idempotency_key,
    request_hash, response_json, created_at_ns, expires_at_ns
)
VALUES (
    $1::text, $2::text, $3::text,
    $4::text, $5::text, $6::bytea,
    $7::jsonb, $8::bigint, $9::bigint
)
`

type InsertPolicyIdempotencyParams struct {
	TenantID       string
	PrincipalKind  string
	PrincipalID    string
	Operation      string
	IdempotencyKey string
	RequestHash    []byte
	ResponseJson   []byte
	CreatedAtNs    int64
	ExpiresAtNs    int64
}

func (q *Queries) InsertPolicyIdempotency(ctx context.Context, arg InsertPolicyIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertPolicyIdempotency,
		arg.TenantID,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResponseJson,
		arg.CreatedAtNs,
		arg.ExpiresAtNs,
	)
	return err
}

const insertResourceGrant = `-- name: InsertResourceGrant :exec
INSERT INTO agent_resource_grants (
    grant_id, tenant_id, subject_kind, subject_id,
    resource_kind, resource_id, action, created_at_ns
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertResourceGrantParams struct {
	GrantID      string
	TenantID     string
	SubjectKind  string
	SubjectID    string
	ResourceKind string
	ResourceID   string
	Action       string
	CreatedAtNs  int64
}

func (q *Queries) InsertResourceGrant(ctx context.Context, arg InsertResourceGrantParams) error {
	_, err := q.db.Exec(ctx, insertResourceGrant,
		arg.GrantID,
		arg.TenantID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Action,
		arg.CreatedAtNs,
	)
	return err
}

const listAgents = `-- name: ListAgents :many
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = $1::text
  AND ($2::text = '' OR left(agent_name, char_length($2::text)) = $2::text)
  AND ($3::text = ''
       OR agent_name > $3::text
       OR (agent_name = $3::text AND agent_id > $4::text))
ORDER BY agent_name, agent_id
LIMIT $5::bigint
`

type ListAgentsParams struct {
	TenantID   string
	NamePrefix string
	AfterName  string
	AfterID    string
	PageLimit  int64
}

type ListAgentsRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int16
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs pgtype.Int8
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents,
		arg.TenantID,
		arg.NamePrefix,
		arg.AfterName,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.TenantID,
			&i.AgentName,
			&i.Status,
			&i.AuthVersion,
			&i.CreatedAtNs,
			&i.UpdatedAtNs,
			&i.DisabledAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT credential_id, tenant_id, agent_id, credential_name, credential_prefix,
       secret_hash, created_at_ns, expires_at_ns, expired_accounted_at_ns,
       revoked_at_ns, last_used_at_ns
FROM agent_credentials
WHERE tenant_id = $1::text
  AND agent_id = $2::text
  AND ($3::text = '' OR credential_id > $3::text)
ORDER BY credential_id
LIMIT $4::bigint
`

type ListCredentialsParams struct {
	TenantID  string
	AgentID   string
	AfterID   string
	PageLimit int64
}

func (q *Queries) ListCredentials(ctx context.Context, arg ListCredentialsParams) ([]AgentCredential, error) {
	rows, err := q.db.Query(ctx, listCredentials,
		arg.TenantID,
		arg.AgentID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCredential{}
	for rows.Next() {
		var i AgentCredential
		if err := rows.Scan(
			&i.CredentialID,
			&i.TenantID,
			&i.AgentID,
			&i.CredentialName,
			&i.CredentialPrefix,
			&i.SecretHash,
			&i.CreatedAtNs,
			&i.ExpiresAtNs,
			&i.ExpiredAccountedAtNs,
			&i.RevokedAtNs,
			&i.LastUsedAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceGrants = `-- name: ListResourceGrants :many
SELECT grant_id, tenant_id, subject_kind, subject_id,
       resource_kind, resource_id, action, created_at_ns
FROM agent_resource_grants
WHERE tenant_id = $1::text
  AND ($2::text = '' OR subject_kind = $2::text)
  AND ($3::text = '' OR subject_id = $3::text)
  AND ($4::text = '' OR resource_kind = $4::text)
  AND ($5::text = '' OR resource_id = $5::text)
  AND ($6::text = '' OR grant_id > $6::text)
ORDER BY grant_id
LIMIT $7::bigint
`

type ListResourceGrantsParams struct {
	TenantID     string
	SubjectKind  string
	SubjectID    string
	ResourceKind string
	ResourceID   string
	AfterID      string
	PageLimit    int64
}

func (q *Queries) ListResourceGrants(ctx context.Context, arg ListResourceGrantsParams) ([]AgentResourceGrant, error) {
	rows, err := q.db.Query(ctx, listResourceGrants,
		arg.TenantID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentResourceGrant{}
	for rows.Next() {
		var i AgentResourceGrant
		if err := rows.Scan(
			&i.GrantID,
			&i.TenantID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Action,
			&i.CreatedAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policyResourceExists = `-- name: PolicyResourceExists :one
SELECT CASE $1::text
    WHEN 'tenant' THEN EXISTS (
        SELECT 1 FROM organizations
        WHERE org_id = $2::text AND org_id = $3::text AND is_active = TRUE
    )
    WHEN 'agent' THEN EXISTS (
        SELECT 1 FROM agents WHERE tenant_id = $2::text AND agent_id = $3::text
    )
    WHEN 'queue' THEN EXISTS (
        SELECT 1 FROM queue_properties WHERE tenant_id = $2::text AND queue_id = $3::text
    )
    WHEN 'topic' THEN EXISTS (
        SELECT 1 FROM topic_properties WHERE tenant_id = $2::text AND topic_id = $3::text
    )
    WHEN 'subscription' THEN EXISTS (
        SELECT 1 FROM topic_subscriptions s
        JOIN topic_properties t ON t.topic_id = s.topic_id
        WHERE t.tenant_id = $2::text AND s.subscription_id = $3::text
    )
    ELSE FALSE
END
`

type PolicyResourceExistsParams struct {
	ResourceKind string
	TenantID     string
	ResourceID   string
}

func (q *Queries) PolicyResourceExists(ctx context.Context, arg PolicyResourceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, policyResourceExists, arg.ResourceKind, arg.TenantID, arg.ResourceID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const policySubjectExists = `-- name: PolicySubjectExists :one
SELECT EXISTS (
    SELECT 1 FROM security_principals
    WHERE tenant_id = $1::text
      AND principal_kind = $2::text
      AND principal_id = $3::text
      AND status = 'active'
)
`

type PolicySubjectExistsParams struct {
	TenantID    string
	SubjectKind string
	SubjectID   string
}

func (q *Queries) PolicySubjectExists(ctx context.Context, arg PolicySubjectExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, policySubjectExists, arg.TenantID, arg.SubjectKind, arg.SubjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeExpiredCredentialUsage = `-- name: RemoveExpiredCredentialUsage :execrows
UPDATE agent_resource_usage
SET active_credential_count = active_credential_count - $1::bigint,
    updated_at_ns = $2::bigint
WHERE tenant_id = $3::text
  AND agent_id = $4::text
  AND active_credential_count >= $1::bigint
`

type RemoveExpiredCredentialUsageParams struct {
	Removed     int64
	UpdatedAtNs int64
	TenantID    string
	AgentID     string
}

func (q *Queries) RemoveExpiredCredentialUsage(ctx context.Context, arg RemoveExpiredCredentialUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeExpiredCredentialUsage,
		arg.Removed,
		arg.UpdatedAtNs,
		arg.TenantID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeCredential = `-- name: RevokeCredential :execrows
UPDATE agent_credentials
SET revoked_at_ns = $1::bigint
WHERE tenant_id = $2::text
  AND agent_id = $3::text
  AND credential_id = $4::text
  AND revoked_at_ns IS NULL
  AND expired_accounted_at_ns IS NULL
`

type RevokeCredentialParams struct {
	RevokedAtNs  int64
	TenantID     string
	AgentID      string
	CredentialID string
}

func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeCredential,
		arg.RevokedAtNs,
		arg.TenantID,
		arg.AgentID,
		arg.CredentialID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchCredential = `-- name: TouchCredential :execrows
UPDATE agent_credentials
SET last_used_at_ns = $1::bigint
WHERE tenant_id = $2::text
  AND agent_id = $3::text
  AND credential_id = $4::text
  AND revoked_at_ns IS NULL
  AND expired_accounted_at_ns IS NULL
  AND (expires_at_ns IS NULL OR expires_at_ns > $1::bigint)
`

type TouchCredentialParams struct {
	UsedAtNs     int64
	TenantID     string
	AgentID      string
	CredentialID string
}

func (q *Queries) TouchCredential(ctx context.Context, arg TouchCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchCredential,
		arg.UsedAtNs,
		arg.TenantID,
		arg.AgentID,
		arg.CredentialID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgentPrincipalStatus = `-- name: UpdateAgentPrincipalStatus :execrows
UPDATE security_principals
SET status = CASE WHEN $1::smallint = 1 THEN 'active' ELSE 'disabled' END,
    updated_at_ns = $2::bigint
WHERE tenant_id = $3::text
  AND principal_kind = 'agent'
  AND principal_id = $4::text
`

type UpdateAgentPrincipalStatusParams struct {
	Status      int16
	UpdatedAtNs int64
	TenantID    string
	AgentID     string
}

func (q *Queries) UpdateAgentPrincipalStatus(ctx context.Context, arg UpdateAgentPrincipalStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAgentPrincipalStatus,
		arg.Status,
		arg.UpdatedAtNs,
		arg.TenantID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgentStatus = `-- name: UpdateAgentStatus :execrows
UPDATE agents
SET status = $1::smallint,
    updated_at_ns = $2::bigint,
    disabled_at_ns = CASE WHEN $1::smallint = 2 THEN $2::bigint ELSE NULL END
WHERE tenant_id = $3::text AND agent_id = $4::text
`

type UpdateAgentStatusParams struct {
	Status      int16
	UpdatedAtNs int64
	TenantID    string
	AgentID     string
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAgentStatus,
		arg.Status,
		arg.UpdatedAtNs,
		arg.TenantID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
