// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgents = `-- name: CountAgents :one
SELECT count(*)
FROM agents
WHERE tenant_id = $1::text
  AND ($2::text = '' OR left(agent_name, char_length($2::text)) = $2::text)
`

type CountAgentsParams struct {
	TenantID   string
	NamePrefix string
}

func (q *Queries) CountAgents(ctx context.Context, arg CountAgentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgents, arg.TenantID, arg.NamePrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (
    agent_id, tenant_id, agent_name, status, auth_version,
    created_by_kind, created_by_id, created_at_ns, updated_at_ns
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAgentParams struct {
	AgentID       string
	TenantID      string
	AgentName     string
	Status        int16
	AuthVersion   int64
	CreatedByKind string
	CreatedByID   string
	CreatedAtNs   int64
	UpdatedAtNs   int64
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.Exec(ctx, createAgent,
		arg.AgentID,
		arg.TenantID,
		arg.AgentName,
		arg.Status,
		arg.AuthVersion,
		arg.CreatedByKind,
		arg.CreatedByID,
		arg.CreatedAtNs,
		arg.UpdatedAtNs,
	)
	return err
}

const createAgentPrincipal = `-- name: CreateAgentPrincipal :exec
INSERT INTO security_principals (
    tenant_id, principal_kind, principal_id, status, roles_json,
    auth_version, updated_at_ns
)
VALUES ($1, 'agent', $2, 'active', '["agent"]'::jsonb, $3, $4)
`

type CreateAgentPrincipalParams struct {
	TenantID    string
	PrincipalID string
	AuthVersion int64
	UpdatedAtNs int64
}

func (q *Queries) CreateAgentPrincipal(ctx context.Context, arg CreateAgentPrincipalParams) error {
	_, err := q.db.Exec(ctx, createAgentPrincipal,
		arg.TenantID,
		arg.PrincipalID,
		arg.AuthVersion,
		arg.UpdatedAtNs,
	)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = $1 AND agent_id = $2
`

type GetAgentParams struct {
	TenantID string
	AgentID  string
}

type GetAgentRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int16
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs pgtype.Int8
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.TenantID, arg.AgentID)
	var i GetAgentRow
	err := row.Scan(
		&i.AgentID,
		&i.TenantID,
		&i.AgentName,
		&i.Status,
		&i.AuthVersion,
		&i.CreatedAtNs,
		&i.UpdatedAtNs,
		&i.DisabledAtNs,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = $1 AND agent_name = $2
`

type GetAgentByNameParams struct {
	TenantID  string
	AgentName string
}

type GetAgentByNameRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int16
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs pgtype.Int8
}

func (q *Queries) GetAgentByName(ctx context.Context, arg GetAgentByNameParams) (GetAgentByNameRow, error) {
	row := q.db.QueryRow(ctx, getAgentByName, arg.TenantID, arg.AgentName)
	var i GetAgentByNameRow
	err := row.Scan(
		&i.AgentID,
		&i.TenantID,
		&i.AgentName,
		&i.Status,
		&i.AuthVersion,
		&i.CreatedAtNs,
		&i.UpdatedAtNs,
		&i.DisabledAtNs,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = $1::text
  AND ($2::text = '' OR left(agent_name, char_length($2::text)) = $2::text)
  AND ($3::text = ''
       OR agent_name > $3::text
       OR (agent_name = $3::text AND agent_id > $4::text))
ORDER BY agent_name, agent_id
LIMIT $5::bigint
`

type ListAgentsParams struct {
	TenantID   string
	NamePrefix string
	AfterName  string
	AfterID    string
	PageLimit  int64
}

type ListAgentsRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int16
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs pgtype.Int8
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents,
		arg.TenantID,
		arg.NamePrefix,
		arg.AfterName,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.TenantID,
			&i.AgentName,
			&i.Status,
			&i.AuthVersion,
			&i.CreatedAtNs,
			&i.UpdatedAtNs,
			&i.DisabledAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentPrincipalStatus = `-- name: UpdateAgentPrincipalStatus :execrows
UPDATE security_principals
SET status = CASE WHEN $1::smallint = 1 THEN 'active' ELSE 'disabled' END,
    updated_at_ns = $2::bigint
WHERE tenant_id = $3::text
  AND principal_kind = 'agent'
  AND principal_id = $4::text
`

type UpdateAgentPrincipalStatusParams struct {
	Status      int16
	UpdatedAtNs int64
	TenantID    string
	AgentID     string
}

func (q *Queries) UpdateAgentPrincipalStatus(ctx context.Context, arg UpdateAgentPrincipalStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAgentPrincipalStatus,
		arg.Status,
		arg.UpdatedAtNs,
		arg.TenantID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgentStatus = `-- name: UpdateAgentStatus :execrows
UPDATE agents
SET status = $1::smallint,
    updated_at_ns = $2::bigint,
    disabled_at_ns = CASE WHEN $1::smallint = 2 THEN $2::bigint ELSE NULL END
WHERE tenant_id = $3::text AND agent_id = $4::text
`

type UpdateAgentStatusParams struct {
	Status      int16
	UpdatedAtNs int64
	TenantID    string
	AgentID     string
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAgentStatus,
		arg.Status,
		arg.UpdatedAtNs,
		arg.TenantID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
