// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type QueuePermission struct {
	QueueID    string
	RoleID     string
	CanSend    bool
	CanReceive bool
	CanPurge   bool
	CanDelete  bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Role struct {
	RoleID    string
	RoleName  string
	CreatedAt pgtype.Timestamptz
}
