// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id, created_at)
VALUES ($1, $2, $3)
`

type AssignRoleToUserParams struct {
	UserID    string
	RoleID    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID, arg.CreatedAt)
	return err
}

const createQueuePermission = `-- name: CreateQueuePermission :exec
INSERT INTO queue_permissions (queue_id, role_id, can_send, can_receive, can_purge, can_delete, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateQueuePermissionParams struct {
	QueueID    string
	RoleID     string
	CanSend    bool
	CanReceive bool
	CanPurge   bool
	CanDelete  bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateQueuePermission(ctx context.Context, arg CreateQueuePermissionParams) error {
	_, err := q.db.Exec(ctx, createQueuePermission,
		arg.QueueID,
		arg.RoleID,
		arg.CanSend,
		arg.CanReceive,
		arg.CanPurge,
		arg.CanDelete,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (role_id, role_name, created_at)
VALUES ($1, $2, $3)
`

type CreateRoleParams struct {
	RoleID    string
	RoleName  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole, arg.RoleID, arg.RoleName, arg.CreatedAt)
	return err
}

const deleteQueuePermission = `-- name: DeleteQueuePermission :execrows
DELETE FROM queue_permissions
WHERE queue_id = $1 AND role_id = $2
`

type DeleteQueuePermissionParams struct {
	QueueID string
	RoleID  string
}

func (q *Queries) DeleteQueuePermission(ctx context.Context, arg DeleteQueuePermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQueuePermission, arg.QueueID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles
WHERE role_id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, roleID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT role_id, role_name, created_at
FROM roles
ORDER BY role_name
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueuePermission = `-- name: GetQueuePermission :one
SELECT queue_id, role_id, can_send, can_receive, can_purge, can_delete, created_at, updated_at
FROM queue_permissions
WHERE queue_id = $1 AND role_id = $2
`

type GetQueuePermissionParams struct {
	QueueID string
	RoleID  string
}

func (q *Queries) GetQueuePermission(ctx context.Context, arg GetQueuePermissionParams) (QueuePermission, error) {
	row := q.db.QueryRow(ctx, getQueuePermission, arg.QueueID, arg.RoleID)
	var i QueuePermission
	err := row.Scan(
		&i.QueueID,
		&i.RoleID,
		&i.CanSend,
		&i.CanReceive,
		&i.CanPurge,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT role_id, role_name, created_at
FROM roles
WHERE role_id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, roleID string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, roleID)
	var i Role
	err := row.Scan(&i.RoleID, &i.RoleName, &i.CreatedAt)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT role_id, role_name, created_at
FROM roles
WHERE role_name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, roleName string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, roleName)
	var i Role
	err := row.Scan(&i.RoleID, &i.RoleName, &i.CreatedAt)
	return i, err
}

const hasQueueDeletePermission = `-- name: HasQueueDeletePermission :one
SELECT COUNT(*)
FROM queue_permissions qp
         INNER JOIN user_roles ur ON qp.role_id = ur.role_id
WHERE ur.user_id = $1 AND qp.queue_id = $2 AND qp.can_delete = TRUE
`

type HasQueueDeletePermissionParams struct {
	UserID  string
	QueueID string
}

func (q *Queries) HasQueueDeletePermission(ctx context.Context, arg HasQueueDeletePermissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, hasQueueDeletePermission, arg.UserID, arg.QueueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasQueuePurgePermission = `-- name: HasQueuePurgePermission :one
SELECT COUNT(*)
FROM queue_permissions qp
         INNER JOIN user_roles ur ON qp.role_id = ur.role_id
WHERE ur.user_id = $1 AND qp.queue_id = $2 AND qp.can_purge = TRUE
`

type HasQueuePurgePermissionParams struct {
	UserID  string
	QueueID string
}

func (q *Queries) HasQueuePurgePermission(ctx context.Context, arg HasQueuePurgePermissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, hasQueuePurgePermission, arg.UserID, arg.QueueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasQueueReceivePermission = `-- name: HasQueueReceivePermission :one
SELECT COUNT(*)
FROM queue_permissions qp
         INNER JOIN user_roles ur ON qp.role_id = ur.role_id
WHERE ur.user_id = $1 AND qp.queue_id = $2 AND qp.can_receive = TRUE
`

type HasQueueReceivePermissionParams struct {
	UserID  string
	QueueID string
}

func (q *Queries) HasQueueReceivePermission(ctx context.Context, arg HasQueueReceivePermissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, hasQueueReceivePermission, arg.UserID, arg.QueueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasQueueSendPermission = `-- name: HasQueueSendPermission :one
SELECT COUNT(*)
FROM queue_permissions qp
         INNER JOIN user_roles ur ON qp.role_id = ur.role_id
WHERE ur.user_id = $1 AND qp.queue_id = $2 AND qp.can_send = TRUE
`

type HasQueueSendPermissionParams struct {
	UserID  string
	QueueID string
}

func (q *Queries) HasQueueSendPermission(ctx context.Context, arg HasQueueSendPermissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, hasQueueSendPermission, arg.UserID, arg.QueueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRoleQueuePermissions = `-- name: ListRoleQueuePermissions :many
SELECT queue_id, role_id, can_send, can_receive, can_purge, can_delete, created_at, updated_at
FROM queue_permissions
WHERE role_id = $1
`

func (q *Queries) ListRoleQueuePermissions(ctx context.Context, roleID string) ([]QueuePermission, error) {
	rows, err := q.db.Query(ctx, listRoleQueuePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueuePermission{}
	for rows.Next() {
		var i QueuePermission
		if err := rows.Scan(
			&i.QueueID,
			&i.RoleID,
			&i.CanSend,
			&i.CanReceive,
			&i.CanPurge,
			&i.CanDelete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.role_id, r.role_name, r.created_at
FROM roles r
         INNER JOIN user_roles ur ON r.role_id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.role_name
`

func (q *Queries) ListUserRoles(ctx context.Context, userID string) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRole = `-- name: ListUsersWithRole :many
SELECT user_id
FROM user_roles
WHERE role_id = $1
`

func (q *Queries) ListUsersWithRole(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsersWithRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :execrows
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID string
	RoleID string
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateQueuePermission = `-- name: UpdateQueuePermission :execrows
UPDATE queue_permissions
SET can_send    = $1,
    can_receive = $2,
    can_purge   = $3,
    can_delete  = $4,
    updated_at  = $5
WHERE queue_id = $6 AND role_id = $7
`

type UpdateQueuePermissionParams struct {
	CanSend    bool
	CanReceive bool
	CanPurge   bool
	CanDelete  bool
	UpdatedAt  pgtype.Timestamptz
	QueueID    string
	RoleID     string
}

func (q *Queries) UpdateQueuePermission(ctx context.Context, arg UpdateQueuePermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQueuePermission,
		arg.CanSend,
		arg.CanReceive,
		arg.CanPurge,
		arg.CanDelete,
		arg.UpdatedAt,
		arg.QueueID,
		arg.RoleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE roles
SET role_name = $1
WHERE role_id = $2
`

type UpdateRoleParams struct {
	RoleName string
	RoleID   string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRole, arg.RoleName, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
