// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthProvider struct {
	ProviderID   string
	ProviderName string
	OrgID        pgtype.Text
	ConfigJson   string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Organization struct {
	OrgID     string
	OrgCode   string
	OrgName   string
	OrgDomain pgtype.Text
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Team struct {
	TeamID      string
	OrgID       string
	TeamName    string
	TeamCode    string
	Description pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
