// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserToTeam = `-- name: AssignUserToTeam :exec
INSERT INTO user_teams (user_id, team_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AssignUserToTeamParams struct {
	UserID    string
	TeamID    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AssignUserToTeam(ctx context.Context, arg AssignUserToTeamParams) error {
	_, err := q.db.Exec(ctx, assignUserToTeam, arg.UserID, arg.TeamID, arg.CreatedAt)
	return err
}

const createOAuthProvider = `-- name: CreateOAuthProvider :exec
INSERT INTO oauth_providers (provider_id, provider_name, org_id, config_json, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOAuthProviderParams struct {
	ProviderID   string
	ProviderName string
	OrgID        pgtype.Text
	ConfigJson   string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateOAuthProvider(ctx context.Context, arg CreateOAuthProviderParams) error {
	_, err := q.db.Exec(ctx, createOAuthProvider,
		arg.ProviderID,
		arg.ProviderName,
		arg.OrgID,
		arg.ConfigJson,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOAuthProvider = `-- name: DeleteOAuthProvider :execrows
DELETE FROM oauth_providers
WHERE provider_id = $1
`

func (q *Queries) DeleteOAuthProvider(ctx context.Context, providerID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthProvider, providerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthProviderByID = `-- name: GetOAuthProviderByID :one
SELECT provider_id, provider_name, org_id, config_json, is_active, created_at, updated_at
FROM oauth_providers
WHERE provider_id = $1
`

func (q *Queries) GetOAuthProviderByID(ctx context.Context, providerID string) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProviderByID, providerID)
	var i OauthProvider
	err := row.Scan(
		&i.ProviderID,
		&i.ProviderName,
		&i.OrgID,
		&i.ConfigJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthProviderByName = `-- name: GetOAuthProviderByName :one
SELECT provider_id, provider_name, org_id, config_json, is_active, created_at, updated_at
FROM oauth_providers
WHERE provider_name = $1 AND (org_id = $2 OR (org_id IS NULL AND $2 = ''))
`

type GetOAuthProviderByNameParams struct {
	ProviderName string
	OrgID        pgtype.Text
}

func (q *Queries) GetOAuthProviderByName(ctx context.Context, arg GetOAuthProviderByNameParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProviderByName, arg.ProviderName, arg.OrgID)
	var i OauthProvider
	err := row.Scan(
		&i.ProviderID,
		&i.ProviderName,
		&i.OrgID,
		&i.ConfigJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByCode = `-- name: GetOrganizationByCode :one
SELECT org_id, org_code, org_name, org_domain, is_active, created_at, updated_at
FROM organizations
WHERE org_code = $1 AND is_active = TRUE
`

func (q *Queries) GetOrganizationByCode(ctx context.Context, orgCode string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByCode, orgCode)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.OrgCode,
		&i.OrgName,
		&i.OrgDomain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByDomain = `-- name: GetOrganizationByDomain :one
SELECT org_id, org_code, org_name, org_domain, is_active, created_at, updated_at
FROM organizations
WHERE org_domain = $1 AND is_active = TRUE
`

func (q *Queries) GetOrganizationByDomain(ctx context.Context, orgDomain pgtype.Text) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByDomain, orgDomain)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.OrgCode,
		&i.OrgName,
		&i.OrgDomain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByCode = `-- name: GetTeamByCode :one
SELECT team_id, org_id, team_name, team_code, description, is_active, created_at, updated_at
FROM teams
WHERE org_id = $1 AND team_code = $2
`

type GetTeamByCodeParams struct {
	OrgID    string
	TeamCode string
}

func (q *Queries) GetTeamByCode(ctx context.Context, arg GetTeamByCodeParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByCode, arg.OrgID, arg.TeamCode)
	var i Team
	err := row.Scan(
		&i.TeamID,
		&i.OrgID,
		&i.TeamName,
		&i.TeamCode,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuthSub = `-- name: GetUserByOAuthSub :one
SELECT user_id, email, org_id, oauth_provider, oauth_sub, is_oauth_user, last_sync_at, created_at, updated_at
FROM users
WHERE oauth_provider = $1 AND oauth_sub = $2
`

type GetUserByOAuthSubParams struct {
	OauthProvider pgtype.Text
	OauthSub      pgtype.Text
}

type GetUserByOAuthSubRow struct {
	UserID        string
	Email         string
	OrgID         pgtype.Text
	OauthProvider pgtype.Text
	OauthSub      pgtype.Text
	IsOauthUser   bool
	LastSyncAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUserByOAuthSub(ctx context.Context, arg GetUserByOAuthSubParams) (GetUserByOAuthSubRow, error) {
	row := q.db.QueryRow(ctx, getUserByOAuthSub, arg.OauthProvider, arg.OauthSub)
	var i GetUserByOAuthSubRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.OrgID,
		&i.OauthProvider,
		&i.OauthSub,
		&i.IsOauthUser,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIDByOAuthSub = `-- name: GetUserIDByOAuthSub :one
SELECT user_id
FROM users
WHERE oauth_provider = $1 AND oauth_sub = $2
`

type GetUserIDByOAuthSubParams struct {
	OauthProvider pgtype.Text
	OauthSub      pgtype.Text
}

func (q *Queries) GetUserIDByOAuthSub(ctx context.Context, arg GetUserIDByOAuthSubParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserIDByOAuthSub, arg.OauthProvider, arg.OauthSub)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserOrgID = `-- name: GetUserOrgID :one
SELECT coalesce(org_id, '')::text AS org_id
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserOrgID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserOrgID, userID)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const getUserSyncStatus = `-- name: GetUserSyncStatus :one
SELECT coalesce(oauth_provider, '')::text AS provider_name, is_oauth_user, last_sync_at
FROM users
WHERE user_id = $1
`

type GetUserSyncStatusRow struct {
	ProviderName string
	IsOauthUser  bool
	LastSyncAt   pgtype.Timestamptz
}

func (q *Queries) GetUserSyncStatus(ctx context.Context, userID string) (GetUserSyncStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserSyncStatus, userID)
	var i GetUserSyncStatusRow
	err := row.Scan(&i.ProviderName, &i.IsOauthUser, &i.LastSyncAt)
	return i, err
}

const insertOAuthUser = `-- name: InsertOAuthUser :exec
INSERT INTO users (user_id, email, password, verified, org_id, oauth_provider, oauth_sub, is_oauth_user, last_sync_at, created_at, updated_at)
VALUES ($1, $2, '', TRUE, $3, $4, $5, TRUE, $6, $7, $8)
`

type InsertOAuthUserParams struct {
	UserID        string
	Email         string
	OrgID         pgtype.Text
	OauthProvider pgtype.Text
	OauthSub      pgtype.Text
	LastSyncAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertOAuthUser(ctx context.Context, arg InsertOAuthUserParams) error {
	_, err := q.db.Exec(ctx, insertOAuthUser,
		arg.UserID,
		arg.Email,
		arg.OrgID,
		arg.OauthProvider,
		arg.OauthSub,
		arg.LastSyncAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listOAuthProvidersByOrg = `-- name: ListOAuthProvidersByOrg :many
SELECT provider_id, provider_name, org_id, config_json, is_active, created_at, updated_at
FROM oauth_providers
WHERE coalesce(org_id, '') = $1::text
ORDER BY provider_name
`

func (q *Queries) ListOAuthProvidersByOrg(ctx context.Context, orgID string) ([]OauthProvider, error) {
	rows, err := q.db.Query(ctx, listOAuthProvidersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthProvider{}
	for rows.Next() {
		var i OauthProvider
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderName,
			&i.OrgID,
			&i.ConfigJson,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT org_id, org_code, org_name, org_domain, is_active, created_at, updated_at
FROM organizations
WHERE is_active = TRUE
ORDER BY org_name
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.OrgID,
			&i.OrgCode,
			&i.OrgName,
			&i.OrgDomain,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderSyncStats = `-- name: ListProviderSyncStats :many
SELECT coalesce(u.oauth_provider, '')::text AS provider_name,
       count(*)::bigint                     AS user_count,
       (SELECT u2.last_sync_at
        FROM users u2
        WHERE u2.oauth_provider = u.oauth_provider
          AND u2.last_sync_at IS NOT NULL
          AND (NOT $1::boolean OR coalesce(u2.org_id, '') = $2::text)
        ORDER BY u2.last_sync_at DESC
        LIMIT 1)                            AS last_sync_at
FROM users u
WHERE u.is_oauth_user = TRUE
  AND (NOT $1::boolean OR coalesce(u.org_id, '') = $2::text)
GROUP BY u.oauth_provider
`

type ListProviderSyncStatsParams struct {
	ScopeOrg bool
	OrgID    string
}

type ListProviderSyncStatsRow struct {
	ProviderName string
	UserCount    int64
	LastSyncAt   pgtype.Timestamptz
}

func (q *Queries) ListProviderSyncStats(ctx context.Context, arg ListProviderSyncStatsParams) ([]ListProviderSyncStatsRow, error) {
	rows, err := q.db.Query(ctx, listProviderSyncStats, arg.ScopeOrg, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderSyncStatsRow{}
	for rows.Next() {
		var i ListProviderSyncStatsRow
		if err := rows.Scan(&i.ProviderName, &i.UserCount, &i.LastSyncAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT team_id, org_id, team_name, team_code, description, is_active, created_at, updated_at
FROM teams
WHERE org_id = $1 AND is_active = TRUE
`

func (q *Queries) ListTeamsByOrg(ctx context.Context, orgID string) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.TeamID,
			&i.OrgID,
			&i.TeamName,
			&i.TeamCode,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.team_id, t.org_id, t.team_name, t.team_code, t.description, t.is_active, t.created_at, t.updated_at
FROM teams t
         INNER JOIN user_teams ut ON t.team_id = ut.team_id
WHERE ut.user_id = $1
`

func (q *Queries) ListUserTeams(ctx context.Context, userID string) ([]Team, error) {
	rows, err := q.db.Query(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.TeamID,
			&i.OrgID,
			&i.TeamName,
			&i.TeamCode,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTeam = `-- name: RemoveUserFromTeam :exec
DELETE FROM user_teams
WHERE user_id = $1 AND team_id = $2
`

type RemoveUserFromTeamParams struct {
	UserID string
	TeamID string
}

func (q *Queries) RemoveUserFromTeam(ctx context.Context, arg RemoveUserFromTeamParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTeam, arg.UserID, arg.TeamID)
	return err
}

const updateOAuthProvider = `-- name: UpdateOAuthProvider :execrows
UPDATE oauth_providers
SET provider_name = $1,
    config_json   = $2,
    is_active     = $3,
    updated_at    = $4
WHERE provider_id = $5
`

type UpdateOAuthProviderParams struct {
	ProviderName string
	ConfigJson   string
	IsActive     bool
	UpdatedAt    pgtype.Timestamptz
	ProviderID   string
}

func (q *Queries) UpdateOAuthProvider(ctx context.Context, arg UpdateOAuthProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOAuthProvider,
		arg.ProviderName,
		arg.ConfigJson,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ProviderID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOAuthUser = `-- name: UpdateOAuthUser :exec
UPDATE users
SET email        = $1,
    org_id       = $2,
    last_sync_at = $3,
    updated_at   = $4
WHERE user_id = $5
`

type UpdateOAuthUserParams struct {
	Email      string
	OrgID      pgtype.Text
	LastSyncAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	UserID     string
}

func (q *Queries) UpdateOAuthUser(ctx context.Context, arg UpdateOAuthUserParams) error {
	_, err := q.db.Exec(ctx, updateOAuthUser,
		arg.Email,
		arg.OrgID,
		arg.LastSyncAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const updateUserLastSync = `-- name: UpdateUserLastSync :exec
UPDATE users
SET last_sync_at = $1,
    updated_at   = $2
WHERE user_id = $3
`

type UpdateUserLastSyncParams struct {
	LastSyncAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	UserID     string
}

func (q *Queries) UpdateUserLastSync(ctx context.Context, arg UpdateUserLastSyncParams) error {
	_, err := q.db.Exec(ctx, updateUserLastSync, arg.LastSyncAt, arg.UpdatedAt, arg.UserID)
	return err
}
