// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package sqlcgen

import (
	"context"
	"time"
)

const assignRoleToUser = `-- name: AssignRoleToUser :execrows
INSERT INTO user_roles (user_id, role_id, created_at)
VALUES (?, ?, ?)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID    string
	RoleID    string
	CreatedAt time.Time
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignRoleToUser, arg.UserID, arg.RoleID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bumpUserAuthVersion = `-- name: BumpUserAuthVersion :execrows
UPDATE users
SET auth_version = auth_version + 1
WHERE user_id = ?
`

func (q *Queries) BumpUserAuthVersion(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, bumpUserAuthVersion, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUsersPerRole = `-- name: CountUsersPerRole :many
SELECT role_id, count(*) AS user_count
FROM user_roles
GROUP BY role_id
`

type CountUsersPerRoleRow struct {
	RoleID    string
	UserCount int64
}

func (q *Queries) CountUsersPerRole(ctx context.Context) ([]CountUsersPerRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, countUsersPerRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUsersPerRoleRow{}
	for rows.Next() {
		var i CountUsersPerRoleRow
		if err := rows.Scan(&i.RoleID, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsersWithRole = `-- name: CountUsersWithRole :one
SELECT count(*)
FROM user_roles
WHERE role_id = ?
`

func (q *Queries) CountUsersWithRole(ctx context.Context, roleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersWithRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQueuePermission = `-- name: CreateQueuePermission :exec
INSERT INTO queue_permissions (queue_id, role_id, can_send, can_receive, can_purge, can_delete, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateQueuePermissionParams struct {
	QueueID    string
	RoleID     string
	CanSend    bool
	CanReceive bool
	CanPurge   bool
	CanDelete  bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateQueuePermission(ctx context.Context, arg CreateQueuePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createQueuePermission,
		arg.QueueID,
		arg.RoleID,
		arg.CanSend,
		arg.CanReceive,
		arg.CanPurge,
		arg.CanDelete,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (role_id, role_name, created_at)
VALUES (?, ?, ?)
`

type CreateRoleParams struct {
	RoleID    string
	RoleName  string
	CreatedAt time.Time
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole, arg.RoleID, arg.RoleName, arg.CreatedAt)
	return err
}

const deleteQueuePermission = `-- name: DeleteQueuePermission :execrows
DELETE FROM queue_permissions
WHERE queue_id = ? AND role_id = ?
`

type DeleteQueuePermissionParams struct {
	QueueID string
	RoleID  string
}

func (q *Queries) DeleteQueuePermission(ctx context.Context, arg DeleteQueuePermissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQueuePermission, arg.QueueID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles
WHERE role_id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, roleID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRole, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRoleQueuePermissions = `-- name: DeleteRoleQueuePermissions :execrows
DELETE FROM queue_permissions
WHERE role_id = ?
`

func (q *Queries) DeleteRoleQueuePermissions(ctx context.Context, roleID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRoleQueuePermissions, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT role_id, role_name, created_at
FROM roles
ORDER BY role_name
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueuePermission = `-- name: GetQueuePermission :one
SELECT queue_id, role_id, can_send, can_receive, can_purge, can_delete, created_at, updated_at
FROM queue_permissions
WHERE queue_id = ? AND role_id = ?
`

type GetQueuePermissionParams struct {
	QueueID string
	RoleID  string
}

func (q *Queries) GetQueuePermission(ctx context.Context, arg GetQueuePermissionParams) (QueuePermission, error) {
	row := q.db.QueryRowContext(ctx, getQueuePermission, arg.QueueID, arg.RoleID)
	var i QueuePermission
	err := row.Scan(
		&i.QueueID,
		&i.RoleID,
		&i.CanSend,
		&i.CanReceive,
		&i.CanPurge,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT role_id, role_name, created_at
FROM roles
WHERE role_id = ?
`

func (q *Queries) GetRoleByID(ctx context.Context, roleID string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, roleID)
	var i Role
	err := row.Scan(&i.RoleID, &i.RoleName, &i.CreatedAt)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT role_id, role_name, created_at
FROM roles
WHERE role_name = ?
`

func (q *Queries) GetRoleByName(ctx context.Context, roleName string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, roleName)
	var i Role
	err := row.Scan(&i.RoleID, &i.RoleName, &i.CreatedAt)
	return i, err
}

const hasQueueDeletePermission = `-- name: HasQueueDeletePermission :one
SELECT COUNT(*)
FROM user_roles ur
         INNER JOIN roles r ON r.role_id = ur.role_id
         INNER JOIN users u ON u.user_id = ur.user_id
         INNER JOIN queue_properties q ON q.queue_id = ?1 AND q.tenant_id = u.org_id
         LEFT JOIN queue_permissions qp ON qp.queue_id = q.queue_id AND qp.role_id = ur.role_id
WHERE ur.user_id = ?2 AND u.status = 'active'
  AND (r.role_name = 'admin' OR COALESCE(qp.can_delete, FALSE) = TRUE)
`

type HasQueueDeletePermissionParams struct {
	QueueID string
	UserID  string
}

func (q *Queries) HasQueueDeletePermission(ctx context.Context, arg HasQueueDeletePermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasQueueDeletePermission, arg.QueueID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasQueuePurgePermission = `-- name: HasQueuePurgePermission :one
SELECT COUNT(*)
FROM user_roles ur
         INNER JOIN roles r ON r.role_id = ur.role_id
         INNER JOIN users u ON u.user_id = ur.user_id
         INNER JOIN queue_properties q ON q.queue_id = ?1 AND q.tenant_id = u.org_id
         LEFT JOIN queue_permissions qp ON qp.queue_id = q.queue_id AND qp.role_id = ur.role_id
WHERE ur.user_id = ?2 AND u.status = 'active'
  AND (r.role_name = 'admin' OR COALESCE(qp.can_purge, FALSE) = TRUE)
`

type HasQueuePurgePermissionParams struct {
	QueueID string
	UserID  string
}

func (q *Queries) HasQueuePurgePermission(ctx context.Context, arg HasQueuePurgePermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasQueuePurgePermission, arg.QueueID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasQueueReceivePermission = `-- name: HasQueueReceivePermission :one
SELECT COUNT(*)
FROM user_roles ur
         INNER JOIN roles r ON r.role_id = ur.role_id
         INNER JOIN users u ON u.user_id = ur.user_id
         INNER JOIN queue_properties q ON q.queue_id = ?1 AND q.tenant_id = u.org_id
         LEFT JOIN queue_permissions qp ON qp.queue_id = q.queue_id AND qp.role_id = ur.role_id
WHERE ur.user_id = ?2 AND u.status = 'active'
  AND (r.role_name = 'admin' OR COALESCE(qp.can_receive, FALSE) = TRUE)
`

type HasQueueReceivePermissionParams struct {
	QueueID string
	UserID  string
}

func (q *Queries) HasQueueReceivePermission(ctx context.Context, arg HasQueueReceivePermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasQueueReceivePermission, arg.QueueID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasQueueSendPermission = `-- name: HasQueueSendPermission :one
SELECT COUNT(*)
FROM user_roles ur
         INNER JOIN roles r ON r.role_id = ur.role_id
         INNER JOIN users u ON u.user_id = ur.user_id
         INNER JOIN queue_properties q ON q.queue_id = ?1 AND q.tenant_id = u.org_id
         LEFT JOIN queue_permissions qp ON qp.queue_id = q.queue_id AND qp.role_id = ur.role_id
WHERE ur.user_id = ?2 AND u.status = 'active'
  AND (r.role_name = 'admin' OR COALESCE(qp.can_send, FALSE) = TRUE)
`

type HasQueueSendPermissionParams struct {
	QueueID string
	UserID  string
}

func (q *Queries) HasQueueSendPermission(ctx context.Context, arg HasQueueSendPermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasQueueSendPermission, arg.QueueID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRoleQueuePermissions = `-- name: ListRoleQueuePermissions :many
SELECT queue_id, role_id, can_send, can_receive, can_purge, can_delete, created_at, updated_at
FROM queue_permissions
WHERE role_id = ?
`

func (q *Queries) ListRoleQueuePermissions(ctx context.Context, roleID string) ([]QueuePermission, error) {
	rows, err := q.db.QueryContext(ctx, listRoleQueuePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueuePermission{}
	for rows.Next() {
		var i QueuePermission
		if err := rows.Scan(
			&i.QueueID,
			&i.RoleID,
			&i.CanSend,
			&i.CanReceive,
			&i.CanPurge,
			&i.CanDelete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.role_id, r.role_name, r.created_at
FROM roles r
         INNER JOIN user_roles ur ON r.role_id = ur.role_id
WHERE ur.user_id = ?
ORDER BY r.role_name
`

func (q *Queries) ListUserRoles(ctx context.Context, userID string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRole = `-- name: ListUsersWithRole :many
SELECT user_id
FROM user_roles
WHERE role_id = ?
`

func (q *Queries) ListUsersWithRole(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :execrows
DELETE FROM user_roles
WHERE user_id = ? AND role_id = ?
`

type RemoveRoleFromUserParams struct {
	UserID string
	RoleID string
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeRoleFromUserUnlessLastHolder = `-- name: RemoveRoleFromUserUnlessLastHolder :execrows
DELETE FROM user_roles
WHERE user_roles.user_id = ?
  AND user_roles.role_id = ?
  AND (SELECT count(*) FROM user_roles other WHERE other.role_id = ?) > 1
`

type RemoveRoleFromUserUnlessLastHolderParams struct {
	UserID   string
	RoleID   string
	RoleID_2 string
}

func (q *Queries) RemoveRoleFromUserUnlessLastHolder(ctx context.Context, arg RemoveRoleFromUserUnlessLastHolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeRoleFromUserUnlessLastHolder, arg.UserID, arg.RoleID, arg.RoleID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateQueuePermission = `-- name: UpdateQueuePermission :execrows
UPDATE queue_permissions
SET can_send    = ?,
    can_receive = ?,
    can_purge   = ?,
    can_delete  = ?,
    updated_at  = ?
WHERE queue_id = ? AND role_id = ?
`

type UpdateQueuePermissionParams struct {
	CanSend    bool
	CanReceive bool
	CanPurge   bool
	CanDelete  bool
	UpdatedAt  time.Time
	QueueID    string
	RoleID     string
}

func (q *Queries) UpdateQueuePermission(ctx context.Context, arg UpdateQueuePermissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateQueuePermission,
		arg.CanSend,
		arg.CanReceive,
		arg.CanPurge,
		arg.CanDelete,
		arg.UpdatedAt,
		arg.QueueID,
		arg.RoleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE roles
SET role_name = ?
WHERE role_id = ?
`

type UpdateRoleParams struct {
	RoleName string
	RoleID   string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRole, arg.RoleName, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertHumanSecurityPrincipal = `-- name: UpsertHumanSecurityPrincipal :exec
INSERT INTO security_principals (
    tenant_id, principal_kind, principal_id, status, roles_json,
    auth_version, updated_at_ns
)
SELECT u.org_id,
       'human',
       u.user_id,
       u.status,
       COALESCE((
           SELECT json_group_array(role_name)
           FROM (
               SELECT r.role_name AS role_name
               FROM user_roles ur
               JOIN roles r ON r.role_id = ur.role_id
               WHERE ur.user_id = u.user_id
               ORDER BY r.role_name
           )
       ), '[]'),
       u.auth_version,
       ?
FROM users u
WHERE u.user_id = ?
ON CONFLICT(tenant_id, principal_kind, principal_id) DO UPDATE SET
    status = excluded.status,
    roles_json = excluded.roles_json,
    auth_version = excluded.auth_version,
    updated_at_ns = excluded.updated_at_ns
`

type UpsertHumanSecurityPrincipalParams struct {
	UpdatedAtNs int64
	UserID      string
}

func (q *Queries) UpsertHumanSecurityPrincipal(ctx context.Context, arg UpsertHumanSecurityPrincipalParams) error {
	_, err := q.db.ExecContext(ctx, upsertHumanSecurityPrincipal, arg.UpdatedAtNs, arg.UserID)
	return err
}

const userHasRole = `-- name: UserHasRole :one
SELECT EXISTS(SELECT 1 FROM user_roles WHERE user_id = ? AND role_id = ?)
`

type UserHasRoleParams struct {
	UserID string
	RoleID string
}

func (q *Queries) UserHasRole(ctx context.Context, arg UserHasRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasRole, arg.UserID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
