// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countActiveCredentials = `-- name: CountActiveCredentials :one
SELECT count(*)
FROM agent_credentials
WHERE tenant_id = cast(?1 AS text)
  AND agent_id = cast(?2 AS text)
  AND revoked_at_ns IS NULL
  AND expired_accounted_at_ns IS NULL
  AND (expires_at_ns IS NULL OR expires_at_ns > cast(?3 AS integer))
`

type CountActiveCredentialsParams struct {
	TenantID string
	AgentID  string
	NowNs    int64
}

func (q *Queries) CountActiveCredentials(ctx context.Context, arg CountActiveCredentialsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveCredentials, arg.TenantID, arg.AgentID, arg.NowNs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgents = `-- name: CountAgents :one
SELECT count(*)
FROM agents
WHERE tenant_id = ?1
  AND (cast(?2 AS text) = ''
       OR substr(agent_name, 1, length(cast(?2 AS text))) = cast(?2 AS text))
`

type CountAgentsParams struct {
	TenantID   string
	NamePrefix string
}

func (q *Queries) CountAgents(ctx context.Context, arg CountAgentsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgents, arg.TenantID, arg.NamePrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (
    agent_id, tenant_id, agent_name, status, auth_version,
    created_by_kind, created_by_id, created_at_ns, updated_at_ns
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentParams struct {
	AgentID       string
	TenantID      string
	AgentName     string
	Status        int64
	AuthVersion   int64
	CreatedByKind string
	CreatedByID   string
	CreatedAtNs   int64
	UpdatedAtNs   int64
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.AgentID,
		arg.TenantID,
		arg.AgentName,
		arg.Status,
		arg.AuthVersion,
		arg.CreatedByKind,
		arg.CreatedByID,
		arg.CreatedAtNs,
		arg.UpdatedAtNs,
	)
	return err
}

const createAgentPrincipal = `-- name: CreateAgentPrincipal :exec
INSERT INTO security_principals (
    tenant_id, principal_kind, principal_id, status, roles_json,
    auth_version, updated_at_ns
)
VALUES (?, 'agent', ?, 'active', '["agent"]', ?, ?)
`

type CreateAgentPrincipalParams struct {
	TenantID    string
	PrincipalID string
	AuthVersion int64
	UpdatedAtNs int64
}

func (q *Queries) CreateAgentPrincipal(ctx context.Context, arg CreateAgentPrincipalParams) error {
	_, err := q.db.ExecContext(ctx, createAgentPrincipal,
		arg.TenantID,
		arg.PrincipalID,
		arg.AuthVersion,
		arg.UpdatedAtNs,
	)
	return err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO agent_credentials (
    credential_id, tenant_id, agent_id, credential_name, credential_prefix,
    secret_hash, created_at_ns, expires_at_ns
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCredentialParams struct {
	CredentialID     string
	TenantID         string
	AgentID          string
	CredentialName   string
	CredentialPrefix string
	SecretHash       []byte
	CreatedAtNs      int64
	ExpiresAtNs      sql.NullInt64
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createCredential,
		arg.CredentialID,
		arg.TenantID,
		arg.AgentID,
		arg.CredentialName,
		arg.CredentialPrefix,
		arg.SecretHash,
		arg.CreatedAtNs,
		arg.ExpiresAtNs,
	)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = ? AND agent_id = ?
`

type GetAgentParams struct {
	TenantID string
	AgentID  string
}

type GetAgentRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int64
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs sql.NullInt64
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRowContext(ctx, getAgent, arg.TenantID, arg.AgentID)
	var i GetAgentRow
	err := row.Scan(
		&i.AgentID,
		&i.TenantID,
		&i.AgentName,
		&i.Status,
		&i.AuthVersion,
		&i.CreatedAtNs,
		&i.UpdatedAtNs,
		&i.DisabledAtNs,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = ? AND agent_name = ?
`

type GetAgentByNameParams struct {
	TenantID  string
	AgentName string
}

type GetAgentByNameRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int64
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs sql.NullInt64
}

func (q *Queries) GetAgentByName(ctx context.Context, arg GetAgentByNameParams) (GetAgentByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentByName, arg.TenantID, arg.AgentName)
	var i GetAgentByNameRow
	err := row.Scan(
		&i.AgentID,
		&i.TenantID,
		&i.AgentName,
		&i.Status,
		&i.AuthVersion,
		&i.CreatedAtNs,
		&i.UpdatedAtNs,
		&i.DisabledAtNs,
	)
	return i, err
}

const getAgentPrincipal = `-- name: GetAgentPrincipal :one
SELECT tenant_id, principal_id, status, auth_version
FROM security_principals
WHERE tenant_id = ? AND principal_kind = 'agent' AND principal_id = ?
`

type GetAgentPrincipalParams struct {
	TenantID    string
	PrincipalID string
}

type GetAgentPrincipalRow struct {
	TenantID    string
	PrincipalID string
	Status      string
	AuthVersion int64
}

func (q *Queries) GetAgentPrincipal(ctx context.Context, arg GetAgentPrincipalParams) (GetAgentPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentPrincipal, arg.TenantID, arg.PrincipalID)
	var i GetAgentPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.PrincipalID,
		&i.Status,
		&i.AuthVersion,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT credential_id, tenant_id, agent_id, credential_name, credential_prefix,
       secret_hash, created_at_ns, expires_at_ns, expired_accounted_at_ns,
       revoked_at_ns, last_used_at_ns
FROM agent_credentials
WHERE credential_id = ?
`

func (q *Queries) GetCredentialByID(ctx context.Context, credentialID string) (AgentCredential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByID, credentialID)
	var i AgentCredential
	err := row.Scan(
		&i.CredentialID,
		&i.TenantID,
		&i.AgentID,
		&i.CredentialName,
		&i.CredentialPrefix,
		&i.SecretHash,
		&i.CreatedAtNs,
		&i.ExpiresAtNs,
		&i.ExpiredAccountedAtNs,
		&i.RevokedAtNs,
		&i.LastUsedAtNs,
	)
	return i, err
}

const getCredentialByPrefix = `-- name: GetCredentialByPrefix :one
SELECT credential_id, tenant_id, agent_id, credential_name, credential_prefix,
       secret_hash, created_at_ns, expires_at_ns, expired_accounted_at_ns,
       revoked_at_ns, last_used_at_ns
FROM agent_credentials
WHERE credential_prefix = ?
`

func (q *Queries) GetCredentialByPrefix(ctx context.Context, credentialPrefix string) (AgentCredential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByPrefix, credentialPrefix)
	var i AgentCredential
	err := row.Scan(
		&i.CredentialID,
		&i.TenantID,
		&i.AgentID,
		&i.CredentialName,
		&i.CredentialPrefix,
		&i.SecretHash,
		&i.CreatedAtNs,
		&i.ExpiresAtNs,
		&i.ExpiredAccountedAtNs,
		&i.RevokedAtNs,
		&i.LastUsedAtNs,
	)
	return i, err
}

const hasResourceGrant = `-- name: HasResourceGrant :one
SELECT EXISTS (
    SELECT 1
    FROM agent_resource_grants
    WHERE tenant_id = cast(?1 AS text)
      AND subject_kind = cast(?2 AS text)
      AND subject_id = cast(?3 AS text)
      AND resource_kind = cast(?4 AS text)
      AND resource_id = cast(?5 AS text)
      AND action = cast(?6 AS text)
)
`

type HasResourceGrantParams struct {
	TenantID     string
	SubjectKind  string
	SubjectID    string
	ResourceKind string
	ResourceID   string
	Action       string
}

func (q *Queries) HasResourceGrant(ctx context.Context, arg HasResourceGrantParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasResourceGrant,
		arg.TenantID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Action,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAgents = `-- name: ListAgents :many
SELECT agent_id, tenant_id, agent_name, status, auth_version,
       created_at_ns, updated_at_ns, disabled_at_ns
FROM agents
WHERE tenant_id = ?1
  AND (cast(?2 AS text) = ''
       OR substr(agent_name, 1, length(cast(?2 AS text))) = cast(?2 AS text))
  AND (cast(?3 AS text) = ''
       OR agent_name > cast(?3 AS text)
       OR (agent_name = cast(?3 AS text)
           AND agent_id > cast(?4 AS text)))
ORDER BY agent_name, agent_id
LIMIT cast(?5 AS integer)
`

type ListAgentsParams struct {
	TenantID   string
	NamePrefix string
	AfterName  string
	AfterID    string
	PageLimit  int64
}

type ListAgentsRow struct {
	AgentID      string
	TenantID     string
	AgentName    string
	Status       int64
	AuthVersion  int64
	CreatedAtNs  int64
	UpdatedAtNs  int64
	DisabledAtNs sql.NullInt64
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgents,
		arg.TenantID,
		arg.NamePrefix,
		arg.AfterName,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.TenantID,
			&i.AgentName,
			&i.Status,
			&i.AuthVersion,
			&i.CreatedAtNs,
			&i.UpdatedAtNs,
			&i.DisabledAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT credential_id, tenant_id, agent_id, credential_name, credential_prefix,
       secret_hash, created_at_ns, expires_at_ns, expired_accounted_at_ns,
       revoked_at_ns, last_used_at_ns
FROM agent_credentials
WHERE tenant_id = cast(?1 AS text)
  AND agent_id = cast(?2 AS text)
  AND (cast(?3 AS text) = ''
       OR credential_id > cast(?3 AS text))
ORDER BY credential_id
LIMIT cast(?4 AS integer)
`

type ListCredentialsParams struct {
	TenantID  string
	AgentID   string
	AfterID   string
	PageLimit int64
}

func (q *Queries) ListCredentials(ctx context.Context, arg ListCredentialsParams) ([]AgentCredential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials,
		arg.TenantID,
		arg.AgentID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCredential{}
	for rows.Next() {
		var i AgentCredential
		if err := rows.Scan(
			&i.CredentialID,
			&i.TenantID,
			&i.AgentID,
			&i.CredentialName,
			&i.CredentialPrefix,
			&i.SecretHash,
			&i.CreatedAtNs,
			&i.ExpiresAtNs,
			&i.ExpiredAccountedAtNs,
			&i.RevokedAtNs,
			&i.LastUsedAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCredential = `-- name: RevokeCredential :execrows
UPDATE agent_credentials
SET revoked_at_ns = cast(?1 AS integer)
WHERE tenant_id = cast(?2 AS text)
  AND agent_id = cast(?3 AS text)
  AND credential_id = cast(?4 AS text)
  AND revoked_at_ns IS NULL
`

type RevokeCredentialParams struct {
	RevokedAtNs  int64
	TenantID     string
	AgentID      string
	CredentialID string
}

func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeCredential,
		arg.RevokedAtNs,
		arg.TenantID,
		arg.AgentID,
		arg.CredentialID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchCredential = `-- name: TouchCredential :execrows
UPDATE agent_credentials
SET last_used_at_ns = cast(?1 AS integer)
WHERE tenant_id = cast(?2 AS text)
  AND agent_id = cast(?3 AS text)
  AND credential_id = cast(?4 AS text)
  AND revoked_at_ns IS NULL
  AND expired_accounted_at_ns IS NULL
  AND (expires_at_ns IS NULL OR expires_at_ns > cast(?1 AS integer))
`

type TouchCredentialParams struct {
	UsedAtNs     int64
	TenantID     string
	AgentID      string
	CredentialID string
}

func (q *Queries) TouchCredential(ctx context.Context, arg TouchCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchCredential,
		arg.UsedAtNs,
		arg.TenantID,
		arg.AgentID,
		arg.CredentialID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAgentPrincipalStatus = `-- name: UpdateAgentPrincipalStatus :execrows
UPDATE security_principals
SET status = CASE WHEN cast(?1 AS integer) = 1 THEN 'active' ELSE 'disabled' END,
    updated_at_ns = cast(?2 AS integer)
WHERE tenant_id = cast(?3 AS text)
  AND principal_kind = 'agent'
  AND principal_id = cast(?4 AS text)
`

type UpdateAgentPrincipalStatusParams struct {
	Status      int64
	UpdatedAtNs int64
	TenantID    string
	AgentID     string
}

func (q *Queries) UpdateAgentPrincipalStatus(ctx context.Context, arg UpdateAgentPrincipalStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAgentPrincipalStatus,
		arg.Status,
		arg.UpdatedAtNs,
		arg.TenantID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAgentStatus = `-- name: UpdateAgentStatus :execrows
UPDATE agents
SET status = cast(?1 AS integer),
    updated_at_ns = cast(?2 AS integer),
    disabled_at_ns = CASE
        WHEN cast(?1 AS integer) = 2 THEN cast(?2 AS integer)
        ELSE NULL
    END
WHERE tenant_id = cast(?3 AS text)
  AND agent_id = cast(?4 AS text)
`

type UpdateAgentStatusParams struct {
	Status      int64
	UpdatedAtNs int64
	TenantID    string
	AgentID     string
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAgentStatus,
		arg.Status,
		arg.UpdatedAtNs,
		arg.TenantID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
