// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type QueueProperty struct {
	QueueID                  string
	QueueName                string
	CreatedAt                pgtype.Timestamptz
	GcAt                     pgtype.Timestamptz
	RetentionPeriodSeconds   int32
	VisibilityTimeoutSeconds int32
	MaxReceiveAttempts       int32
	DropPolicy               int32
	DeadLetterQueueID        pgtype.Text
	TenantID                 string
	CreatedByKind            string
	CreatedByID              string
}
