// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queue.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQueueProperties = `-- name: CountQueueProperties :one
SELECT COUNT(*)
FROM queue_properties
`

func (q *Queries) CountQueueProperties(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQueueProperties)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteQueueProperties = `-- name: DeleteQueueProperties :execrows
DELETE FROM queue_properties
WHERE queue_id = $1
`

func (q *Queries) DeleteQueueProperties(ctx context.Context, queueID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQueueProperties, queueID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQueuePropertiesByID = `-- name: GetQueuePropertiesByID :one
SELECT queue_id,
       queue_name,
       created_at,
       gc_at,
       retention_period_seconds,
       visibility_timeout_seconds,
       max_receive_attempts,
       drop_policy,
       dead_letter_queue_id
FROM queue_properties
WHERE queue_id = $1
`

func (q *Queries) GetQueuePropertiesByID(ctx context.Context, queueID string) (QueueProperty, error) {
	row := q.db.QueryRow(ctx, getQueuePropertiesByID, queueID)
	var i QueueProperty
	err := row.Scan(
		&i.QueueID,
		&i.QueueName,
		&i.CreatedAt,
		&i.GcAt,
		&i.RetentionPeriodSeconds,
		&i.VisibilityTimeoutSeconds,
		&i.MaxReceiveAttempts,
		&i.DropPolicy,
		&i.DeadLetterQueueID,
	)
	return i, err
}

const getQueuePropertiesByName = `-- name: GetQueuePropertiesByName :one
SELECT queue_id,
       queue_name,
       created_at,
       gc_at,
       retention_period_seconds,
       visibility_timeout_seconds,
       max_receive_attempts,
       drop_policy,
       dead_letter_queue_id
FROM queue_properties
WHERE queue_name = $1
`

func (q *Queries) GetQueuePropertiesByName(ctx context.Context, queueName string) (QueueProperty, error) {
	row := q.db.QueryRow(ctx, getQueuePropertiesByName, queueName)
	var i QueueProperty
	err := row.Scan(
		&i.QueueID,
		&i.QueueName,
		&i.CreatedAt,
		&i.GcAt,
		&i.RetentionPeriodSeconds,
		&i.VisibilityTimeoutSeconds,
		&i.MaxReceiveAttempts,
		&i.DropPolicy,
		&i.DeadLetterQueueID,
	)
	return i, err
}

const insertQueueProperties = `-- name: InsertQueueProperties :exec
INSERT INTO queue_properties (queue_id,
                              queue_name,
                              retention_period_seconds,
                              visibility_timeout_seconds,
                              max_receive_attempts,
                              drop_policy,
                              dead_letter_queue_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertQueuePropertiesParams struct {
	QueueID                  string
	QueueName                string
	RetentionPeriodSeconds   int32
	VisibilityTimeoutSeconds int32
	MaxReceiveAttempts       int32
	DropPolicy               int32
	DeadLetterQueueID        pgtype.Text
}

func (q *Queries) InsertQueueProperties(ctx context.Context, arg InsertQueuePropertiesParams) error {
	_, err := q.db.Exec(ctx, insertQueueProperties,
		arg.QueueID,
		arg.QueueName,
		arg.RetentionPeriodSeconds,
		arg.VisibilityTimeoutSeconds,
		arg.MaxReceiveAttempts,
		arg.DropPolicy,
		arg.DeadLetterQueueID,
	)
	return err
}

const selectQueuesForGC = `-- name: SelectQueuesForGC :many
SELECT queue_id
FROM queue_properties
WHERE gc_at < $1
ORDER BY gc_at
LIMIT $2 OFFSET $3
`

type SelectQueuesForGCParams struct {
	GcAt   pgtype.Timestamptz
	Limit  int32
	Offset int32
}

func (q *Queries) SelectQueuesForGC(ctx context.Context, arg SelectQueuesForGCParams) ([]string, error) {
	rows, err := q.db.Query(ctx, selectQueuesForGC, arg.GcAt, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var queue_id string
		if err := rows.Scan(&queue_id); err != nil {
			return nil, err
		}
		items = append(items, queue_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueuePropertiesGCAt = `-- name: UpdateQueuePropertiesGCAt :execrows
UPDATE queue_properties
SET gc_at = now()
WHERE queue_id = $1
`

func (q *Queries) UpdateQueuePropertiesGCAt(ctx context.Context, queueID string) (int64, error) {
	result, err := q.db.Exec(ctx, updateQueuePropertiesGCAt, queueID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
