// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quota.sql

package sqlcgen

import (
	"context"
)

const getQuotaIdempotency = `-- name: GetQuotaIdempotency :one
SELECT request_hash, response_json
FROM agent_idempotency
WHERE tenant_id = $1::text
  AND principal_kind = 'system'
  AND principal_id = 'quota'
  AND operation = $2::text
  AND idempotency_key = $3::text
  AND expires_at_ns > $4::bigint
`

type GetQuotaIdempotencyParams struct {
	TenantID       string
	Operation      string
	IdempotencyKey string
	NowNs          int64
}

type GetQuotaIdempotencyRow struct {
	RequestHash  []byte
	ResponseJson []byte
}

func (q *Queries) GetQuotaIdempotency(ctx context.Context, arg GetQuotaIdempotencyParams) (GetQuotaIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getQuotaIdempotency,
		arg.TenantID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.NowNs,
	)
	var i GetQuotaIdempotencyRow
	err := row.Scan(&i.RequestHash, &i.ResponseJson)
	return i, err
}

const incrementQuotaWindow = `-- name: IncrementQuotaWindow :one
UPDATE quota_windows
SET used = used + $1::bigint
WHERE tenant_id = $2::text
  AND action = $3::text
  AND window_started_at_ns = $4::bigint
  AND used <= $5::bigint - $1::bigint
RETURNING used
`

type IncrementQuotaWindowParams struct {
	Units             int64
	TenantID          string
	Action            string
	WindowStartedAtNs int64
	QuotaLimit        int64
}

func (q *Queries) IncrementQuotaWindow(ctx context.Context, arg IncrementQuotaWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementQuotaWindow,
		arg.Units,
		arg.TenantID,
		arg.Action,
		arg.WindowStartedAtNs,
		arg.QuotaLimit,
	)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const insertQuotaIdempotency = `-- name: InsertQuotaIdempotency :exec
INSERT INTO agent_idempotency (
    tenant_id, principal_kind, principal_id, operation, idempotency_key,
    request_hash, response_json, created_at_ns, expires_at_ns
)
VALUES (
    $1::text,
    'system',
    'quota',
    $2::text,
    $3::text,
    $4::bytea,
    $5::jsonb,
    $6::bigint,
    $7::bigint
)
`

type InsertQuotaIdempotencyParams struct {
	TenantID       string
	Operation      string
	IdempotencyKey string
	RequestHash    []byte
	ResponseJson   []byte
	CreatedAtNs    int64
	ExpiresAtNs    int64
}

func (q *Queries) InsertQuotaIdempotency(ctx context.Context, arg InsertQuotaIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertQuotaIdempotency,
		arg.TenantID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResponseJson,
		arg.CreatedAtNs,
		arg.ExpiresAtNs,
	)
	return err
}

const insertQuotaWindow = `-- name: InsertQuotaWindow :one
INSERT INTO quota_windows (tenant_id, action, window_started_at_ns, used)
SELECT
    $1::text,
    $2::text,
    $3::bigint,
    $4::bigint
WHERE $4::bigint <= $5::bigint
ON CONFLICT (tenant_id, action, window_started_at_ns) DO NOTHING
RETURNING used
`

type InsertQuotaWindowParams struct {
	TenantID          string
	Action            string
	WindowStartedAtNs int64
	Units             int64
	QuotaLimit        int64
}

func (q *Queries) InsertQuotaWindow(ctx context.Context, arg InsertQuotaWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertQuotaWindow,
		arg.TenantID,
		arg.Action,
		arg.WindowStartedAtNs,
		arg.Units,
		arg.QuotaLimit,
	)
	var used int64
	err := row.Scan(&used)
	return used, err
}
