// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type OauthProvider struct {
	ProviderID   string
	ProviderName string
	OrgID        sql.NullString
	ConfigJson   string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Organization struct {
	OrgID     string
	OrgCode   string
	OrgName   string
	OrgDomain sql.NullString
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Team struct {
	TeamID      string
	OrgID       string
	TeamName    string
	TeamCode    string
	Description sql.NullString
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
