// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const assignUserToTeam = `-- name: AssignUserToTeam :exec
INSERT INTO user_teams (user_id, team_id, created_at)
VALUES (?, ?, ?)
ON CONFLICT DO NOTHING
`

type AssignUserToTeamParams struct {
	UserID    string
	TeamID    string
	CreatedAt time.Time
}

func (q *Queries) AssignUserToTeam(ctx context.Context, arg AssignUserToTeamParams) error {
	_, err := q.db.ExecContext(ctx, assignUserToTeam, arg.UserID, arg.TeamID, arg.CreatedAt)
	return err
}

const createOAuthProvider = `-- name: CreateOAuthProvider :exec
INSERT INTO oauth_providers (provider_id, provider_name, org_id, config_json, is_active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateOAuthProviderParams struct {
	ProviderID   string
	ProviderName string
	OrgID        sql.NullString
	ConfigJson   string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateOAuthProvider(ctx context.Context, arg CreateOAuthProviderParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthProvider,
		arg.ProviderID,
		arg.ProviderName,
		arg.OrgID,
		arg.ConfigJson,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOAuthProvider = `-- name: DeleteOAuthProvider :execrows
DELETE FROM oauth_providers
WHERE provider_id = ?
`

func (q *Queries) DeleteOAuthProvider(ctx context.Context, providerID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOAuthProvider, providerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOAuthProviderByName = `-- name: GetOAuthProviderByName :one
SELECT provider_id, provider_name, org_id, config_json, is_active, created_at, updated_at
FROM oauth_providers
WHERE provider_name = ? AND (org_id = ? OR (org_id IS NULL AND ? = ''))
`

type GetOAuthProviderByNameParams struct {
	ProviderName string
	OrgID        sql.NullString
	Column3      interface{}
}

func (q *Queries) GetOAuthProviderByName(ctx context.Context, arg GetOAuthProviderByNameParams) (OauthProvider, error) {
	row := q.db.QueryRowContext(ctx, getOAuthProviderByName, arg.ProviderName, arg.OrgID, arg.Column3)
	var i OauthProvider
	err := row.Scan(
		&i.ProviderID,
		&i.ProviderName,
		&i.OrgID,
		&i.ConfigJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByCode = `-- name: GetOrganizationByCode :one
SELECT org_id, org_code, org_name, org_domain, is_active, created_at, updated_at
FROM organizations
WHERE org_code = ? AND is_active = TRUE
`

func (q *Queries) GetOrganizationByCode(ctx context.Context, orgCode string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByCode, orgCode)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.OrgCode,
		&i.OrgName,
		&i.OrgDomain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByDomain = `-- name: GetOrganizationByDomain :one
SELECT org_id, org_code, org_name, org_domain, is_active, created_at, updated_at
FROM organizations
WHERE org_domain = ? AND is_active = TRUE
`

func (q *Queries) GetOrganizationByDomain(ctx context.Context, orgDomain sql.NullString) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByDomain, orgDomain)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.OrgCode,
		&i.OrgName,
		&i.OrgDomain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByCode = `-- name: GetTeamByCode :one
SELECT team_id, org_id, team_name, team_code, description, is_active, created_at, updated_at
FROM teams
WHERE org_id = ? AND team_code = ?
`

type GetTeamByCodeParams struct {
	OrgID    string
	TeamCode string
}

func (q *Queries) GetTeamByCode(ctx context.Context, arg GetTeamByCodeParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByCode, arg.OrgID, arg.TeamCode)
	var i Team
	err := row.Scan(
		&i.TeamID,
		&i.OrgID,
		&i.TeamName,
		&i.TeamCode,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuthSub = `-- name: GetUserByOAuthSub :one
SELECT user_id, email, org_id, oauth_provider, oauth_sub, is_oauth_user, last_sync_at, created_at, updated_at
FROM users
WHERE oauth_provider = ? AND oauth_sub = ?
`

type GetUserByOAuthSubParams struct {
	OauthProvider sql.NullString
	OauthSub      sql.NullString
}

type GetUserByOAuthSubRow struct {
	UserID        string
	Email         string
	OrgID         sql.NullString
	OauthProvider sql.NullString
	OauthSub      sql.NullString
	IsOauthUser   bool
	LastSyncAt    sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByOAuthSub(ctx context.Context, arg GetUserByOAuthSubParams) (GetUserByOAuthSubRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByOAuthSub, arg.OauthProvider, arg.OauthSub)
	var i GetUserByOAuthSubRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.OrgID,
		&i.OauthProvider,
		&i.OauthSub,
		&i.IsOauthUser,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIDByOAuthSub = `-- name: GetUserIDByOAuthSub :one
SELECT user_id
FROM users
WHERE oauth_provider = ? AND oauth_sub = ?
`

type GetUserIDByOAuthSubParams struct {
	OauthProvider sql.NullString
	OauthSub      sql.NullString
}

func (q *Queries) GetUserIDByOAuthSub(ctx context.Context, arg GetUserIDByOAuthSubParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByOAuthSub, arg.OauthProvider, arg.OauthSub)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const insertOAuthUser = `-- name: InsertOAuthUser :exec
INSERT INTO users (user_id, email, password, verified, org_id, oauth_provider, oauth_sub, is_oauth_user, last_sync_at, created_at, updated_at)
VALUES (?, ?, '', TRUE, ?, ?, ?, TRUE, ?, ?, ?)
`

type InsertOAuthUserParams struct {
	UserID        string
	Email         string
	OrgID         sql.NullString
	OauthProvider sql.NullString
	OauthSub      sql.NullString
	LastSyncAt    sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertOAuthUser(ctx context.Context, arg InsertOAuthUserParams) error {
	_, err := q.db.ExecContext(ctx, insertOAuthUser,
		arg.UserID,
		arg.Email,
		arg.OrgID,
		arg.OauthProvider,
		arg.OauthSub,
		arg.LastSyncAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listOAuthProvidersByOrg = `-- name: ListOAuthProvidersByOrg :many
SELECT provider_id, provider_name, org_id, config_json, is_active, created_at, updated_at
FROM oauth_providers
WHERE org_id = ?
`

func (q *Queries) ListOAuthProvidersByOrg(ctx context.Context, orgID sql.NullString) ([]OauthProvider, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthProvidersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthProvider{}
	for rows.Next() {
		var i OauthProvider
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderName,
			&i.OrgID,
			&i.ConfigJson,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT team_id, org_id, team_name, team_code, description, is_active, created_at, updated_at
FROM teams
WHERE org_id = ? AND is_active = TRUE
`

func (q *Queries) ListTeamsByOrg(ctx context.Context, orgID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.TeamID,
			&i.OrgID,
			&i.TeamName,
			&i.TeamCode,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.team_id, t.org_id, t.team_name, t.team_code, t.description, t.is_active, t.created_at, t.updated_at
FROM teams t
         INNER JOIN user_teams ut ON t.team_id = ut.team_id
WHERE ut.user_id = ?
`

func (q *Queries) ListUserTeams(ctx context.Context, userID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.TeamID,
			&i.OrgID,
			&i.TeamName,
			&i.TeamCode,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTeam = `-- name: RemoveUserFromTeam :exec
DELETE FROM user_teams
WHERE user_id = ? AND team_id = ?
`

type RemoveUserFromTeamParams struct {
	UserID string
	TeamID string
}

func (q *Queries) RemoveUserFromTeam(ctx context.Context, arg RemoveUserFromTeamParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromTeam, arg.UserID, arg.TeamID)
	return err
}

const updateOAuthProvider = `-- name: UpdateOAuthProvider :execrows
UPDATE oauth_providers
SET config_json = ?,
    is_active   = ?,
    updated_at  = ?
WHERE provider_id = ?
`

type UpdateOAuthProviderParams struct {
	ConfigJson string
	IsActive   bool
	UpdatedAt  time.Time
	ProviderID string
}

func (q *Queries) UpdateOAuthProvider(ctx context.Context, arg UpdateOAuthProviderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOAuthProvider,
		arg.ConfigJson,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ProviderID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOAuthUser = `-- name: UpdateOAuthUser :exec
UPDATE users
SET email        = ?,
    org_id       = ?,
    last_sync_at = ?,
    updated_at   = ?
WHERE user_id = ?
`

type UpdateOAuthUserParams struct {
	Email      string
	OrgID      sql.NullString
	LastSyncAt sql.NullTime
	UpdatedAt  time.Time
	UserID     string
}

func (q *Queries) UpdateOAuthUser(ctx context.Context, arg UpdateOAuthUserParams) error {
	_, err := q.db.ExecContext(ctx, updateOAuthUser,
		arg.Email,
		arg.OrgID,
		arg.LastSyncAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const updateUserLastSync = `-- name: UpdateUserLastSync :exec
UPDATE users
SET last_sync_at = ?,
    updated_at   = ?
WHERE user_id = ?
`

type UpdateUserLastSyncParams struct {
	LastSyncAt sql.NullTime
	UpdatedAt  time.Time
	UserID     string
}

func (q *Queries) UpdateUserLastSync(ctx context.Context, arg UpdateUserLastSyncParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastSync, arg.LastSyncAt, arg.UpdatedAt, arg.UserID)
	return err
}
