// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent/v1/messaging.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_CreateAgent_FullMethodName             = "/agent.v1.AgentService/CreateAgent"
	AgentService_GetAgent_FullMethodName                = "/agent.v1.AgentService/GetAgent"
	AgentService_ListAgents_FullMethodName              = "/agent.v1.AgentService/ListAgents"
	AgentService_SetAgentStatus_FullMethodName          = "/agent.v1.AgentService/SetAgentStatus"
	AgentService_CreateAgentCredential_FullMethodName   = "/agent.v1.AgentService/CreateAgentCredential"
	AgentService_ListAgentCredentials_FullMethodName    = "/agent.v1.AgentService/ListAgentCredentials"
	AgentService_RegisterAgentCredential_FullMethodName = "/agent.v1.AgentService/RegisterAgentCredential"
	AgentService_RevokeAgentCredential_FullMethodName   = "/agent.v1.AgentService/RevokeAgentCredential"
	AgentService_ExchangeAgentCredential_FullMethodName = "/agent.v1.AgentService/ExchangeAgentCredential"
	AgentService_CreateGrant_FullMethodName             = "/agent.v1.AgentService/CreateGrant"
	AgentService_ListGrants_FullMethodName              = "/agent.v1.AgentService/ListGrants"
	AgentService_DeleteGrant_FullMethodName             = "/agent.v1.AgentService/DeleteGrant"
	AgentService_SendToAgent_FullMethodName             = "/agent.v1.AgentService/SendToAgent"
	AgentService_ReceiveInbox_FullMethodName            = "/agent.v1.AgentService/ReceiveInbox"
	AgentService_ListenInbox_FullMethodName             = "/agent.v1.AgentService/ListenInbox"
	AgentService_AckInbox_FullMethodName                = "/agent.v1.AgentService/AckInbox"
	AgentService_NackInbox_FullMethodName               = "/agent.v1.AgentService/NackInbox"
	AgentService_ExtendInboxLease_FullMethodName        = "/agent.v1.AgentService/ExtendInboxLease"
	AgentService_SubscribeAgent_FullMethodName          = "/agent.v1.AgentService/SubscribeAgent"
	AgentService_UnsubscribeAgent_FullMethodName        = "/agent.v1.AgentService/UnsubscribeAgent"
	AgentService_ListAgentSubscriptions_FullMethodName  = "/agent.v1.AgentService/ListAgentSubscriptions"
	AgentService_ListAgentDeadLetters_FullMethodName    = "/agent.v1.AgentService/ListAgentDeadLetters"
	AgentService_ReplayAgentDeadLetter_FullMethodName   = "/agent.v1.AgentService/ReplayAgentDeadLetter"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	SetAgentStatus(ctx context.Context, in *SetAgentStatusRequest, opts ...grpc.CallOption) (*SetAgentStatusResponse, error)
	CreateAgentCredential(ctx context.Context, in *CreateAgentCredentialRequest, opts ...grpc.CallOption) (*CreateAgentCredentialResponse, error)
	ListAgentCredentials(ctx context.Context, in *ListAgentCredentialsRequest, opts ...grpc.CallOption) (*ListAgentCredentialsResponse, error)
	RegisterAgentCredential(ctx context.Context, in *RegisterAgentCredentialRequest, opts ...grpc.CallOption) (*RegisterAgentCredentialResponse, error)
	RevokeAgentCredential(ctx context.Context, in *RevokeAgentCredentialRequest, opts ...grpc.CallOption) (*RevokeAgentCredentialResponse, error)
	ExchangeAgentCredential(ctx context.Context, in *ExchangeAgentCredentialRequest, opts ...grpc.CallOption) (*ExchangeAgentCredentialResponse, error)
	CreateGrant(ctx context.Context, in *CreateGrantRequest, opts ...grpc.CallOption) (*CreateGrantResponse, error)
	ListGrants(ctx context.Context, in *ListGrantsRequest, opts ...grpc.CallOption) (*ListGrantsResponse, error)
	DeleteGrant(ctx context.Context, in *DeleteGrantRequest, opts ...grpc.CallOption) (*DeleteGrantResponse, error)
	SendToAgent(ctx context.Context, in *SendToAgentRequest, opts ...grpc.CallOption) (*SendToAgentResponse, error)
	ReceiveInbox(ctx context.Context, in *ReceiveInboxRequest, opts ...grpc.CallOption) (*ReceiveInboxResponse, error)
	ListenInbox(ctx context.Context, in *ListenInboxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenInboxResponse], error)
	AckInbox(ctx context.Context, in *AckInboxRequest, opts ...grpc.CallOption) (*AckInboxResponse, error)
	NackInbox(ctx context.Context, in *NackInboxRequest, opts ...grpc.CallOption) (*NackInboxResponse, error)
	ExtendInboxLease(ctx context.Context, in *ExtendInboxLeaseRequest, opts ...grpc.CallOption) (*ExtendInboxLeaseResponse, error)
	SubscribeAgent(ctx context.Context, in *SubscribeAgentRequest, opts ...grpc.CallOption) (*SubscribeAgentResponse, error)
	UnsubscribeAgent(ctx context.Context, in *UnsubscribeAgentRequest, opts ...grpc.CallOption) (*UnsubscribeAgentResponse, error)
	ListAgentSubscriptions(ctx context.Context, in *ListAgentSubscriptionsRequest, opts ...grpc.CallOption) (*ListAgentSubscriptionsResponse, error)
	ListAgentDeadLetters(ctx context.Context, in *ListAgentDeadLettersRequest, opts ...grpc.CallOption) (*ListAgentDeadLettersResponse, error)
	ReplayAgentDeadLetter(ctx context.Context, in *ReplayAgentDeadLetterRequest, opts ...grpc.CallOption) (*ReplayAgentDeadLetterResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SetAgentStatus(ctx context.Context, in *SetAgentStatusRequest, opts ...grpc.CallOption) (*SetAgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAgentStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_SetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateAgentCredential(ctx context.Context, in *CreateAgentCredentialRequest, opts ...grpc.CallOption) (*CreateAgentCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentCredentialResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateAgentCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgentCredentials(ctx context.Context, in *ListAgentCredentialsRequest, opts ...grpc.CallOption) (*ListAgentCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentCredentialsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgentCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RegisterAgentCredential(ctx context.Context, in *RegisterAgentCredentialRequest, opts ...grpc.CallOption) (*RegisterAgentCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentCredentialResponse)
	err := c.cc.Invoke(ctx, AgentService_RegisterAgentCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RevokeAgentCredential(ctx context.Context, in *RevokeAgentCredentialRequest, opts ...grpc.CallOption) (*RevokeAgentCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAgentCredentialResponse)
	err := c.cc.Invoke(ctx, AgentService_RevokeAgentCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExchangeAgentCredential(ctx context.Context, in *ExchangeAgentCredentialRequest, opts ...grpc.CallOption) (*ExchangeAgentCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeAgentCredentialResponse)
	err := c.cc.Invoke(ctx, AgentService_ExchangeAgentCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateGrant(ctx context.Context, in *CreateGrantRequest, opts ...grpc.CallOption) (*CreateGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGrantResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListGrants(ctx context.Context, in *ListGrantsRequest, opts ...grpc.CallOption) (*ListGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGrantsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteGrant(ctx context.Context, in *DeleteGrantRequest, opts ...grpc.CallOption) (*DeleteGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGrantResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SendToAgent(ctx context.Context, in *SendToAgentRequest, opts ...grpc.CallOption) (*SendToAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_SendToAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReceiveInbox(ctx context.Context, in *ReceiveInboxRequest, opts ...grpc.CallOption) (*ReceiveInboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveInboxResponse)
	err := c.cc.Invoke(ctx, AgentService_ReceiveInbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListenInbox(ctx context.Context, in *ListenInboxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenInboxResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ListenInbox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenInboxRequest, ListenInboxResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ListenInboxClient = grpc.ServerStreamingClient[ListenInboxResponse]

func (c *agentServiceClient) AckInbox(ctx context.Context, in *AckInboxRequest, opts ...grpc.CallOption) (*AckInboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckInboxResponse)
	err := c.cc.Invoke(ctx, AgentService_AckInbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) NackInbox(ctx context.Context, in *NackInboxRequest, opts ...grpc.CallOption) (*NackInboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NackInboxResponse)
	err := c.cc.Invoke(ctx, AgentService_NackInbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExtendInboxLease(ctx context.Context, in *ExtendInboxLeaseRequest, opts ...grpc.CallOption) (*ExtendInboxLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendInboxLeaseResponse)
	err := c.cc.Invoke(ctx, AgentService_ExtendInboxLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SubscribeAgent(ctx context.Context, in *SubscribeAgentRequest, opts ...grpc.CallOption) (*SubscribeAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_SubscribeAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UnsubscribeAgent(ctx context.Context, in *UnsubscribeAgentRequest, opts ...grpc.CallOption) (*UnsubscribeAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_UnsubscribeAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgentSubscriptions(ctx context.Context, in *ListAgentSubscriptionsRequest, opts ...grpc.CallOption) (*ListAgentSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentSubscriptionsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgentSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgentDeadLetters(ctx context.Context, in *ListAgentDeadLettersRequest, opts ...grpc.CallOption) (*ListAgentDeadLettersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentDeadLettersResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgentDeadLetters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReplayAgentDeadLetter(ctx context.Context, in *ReplayAgentDeadLetterRequest, opts ...grpc.CallOption) (*ReplayAgentDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayAgentDeadLetterResponse)
	err := c.cc.Invoke(ctx, AgentService_ReplayAgentDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error)
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	SetAgentStatus(context.Context, *SetAgentStatusRequest) (*SetAgentStatusResponse, error)
	CreateAgentCredential(context.Context, *CreateAgentCredentialRequest) (*CreateAgentCredentialResponse, error)
	ListAgentCredentials(context.Context, *ListAgentCredentialsRequest) (*ListAgentCredentialsResponse, error)
	RegisterAgentCredential(context.Context, *RegisterAgentCredentialRequest) (*RegisterAgentCredentialResponse, error)
	RevokeAgentCredential(context.Context, *RevokeAgentCredentialRequest) (*RevokeAgentCredentialResponse, error)
	ExchangeAgentCredential(context.Context, *ExchangeAgentCredentialRequest) (*ExchangeAgentCredentialResponse, error)
	CreateGrant(context.Context, *CreateGrantRequest) (*CreateGrantResponse, error)
	ListGrants(context.Context, *ListGrantsRequest) (*ListGrantsResponse, error)
	DeleteGrant(context.Context, *DeleteGrantRequest) (*DeleteGrantResponse, error)
	SendToAgent(context.Context, *SendToAgentRequest) (*SendToAgentResponse, error)
	ReceiveInbox(context.Context, *ReceiveInboxRequest) (*ReceiveInboxResponse, error)
	ListenInbox(*ListenInboxRequest, grpc.ServerStreamingServer[ListenInboxResponse]) error
	AckInbox(context.Context, *AckInboxRequest) (*AckInboxResponse, error)
	NackInbox(context.Context, *NackInboxRequest) (*NackInboxResponse, error)
	ExtendInboxLease(context.Context, *ExtendInboxLeaseRequest) (*ExtendInboxLeaseResponse, error)
	SubscribeAgent(context.Context, *SubscribeAgentRequest) (*SubscribeAgentResponse, error)
	UnsubscribeAgent(context.Context, *UnsubscribeAgentRequest) (*UnsubscribeAgentResponse, error)
	ListAgentSubscriptions(context.Context, *ListAgentSubscriptionsRequest) (*ListAgentSubscriptionsResponse, error)
	ListAgentDeadLetters(context.Context, *ListAgentDeadLettersRequest) (*ListAgentDeadLettersResponse, error)
	ReplayAgentDeadLetter(context.Context, *ReplayAgentDeadLetterRequest) (*ReplayAgentDeadLetterResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAgentServiceServer) GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentServiceServer) SetAgentStatus(context.Context, *SetAgentStatusRequest) (*SetAgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAgentStatus not implemented")
}
func (UnimplementedAgentServiceServer) CreateAgentCredential(context.Context, *CreateAgentCredentialRequest) (*CreateAgentCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgentCredential not implemented")
}
func (UnimplementedAgentServiceServer) ListAgentCredentials(context.Context, *ListAgentCredentialsRequest) (*ListAgentCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentCredentials not implemented")
}
func (UnimplementedAgentServiceServer) RegisterAgentCredential(context.Context, *RegisterAgentCredentialRequest) (*RegisterAgentCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgentCredential not implemented")
}
func (UnimplementedAgentServiceServer) RevokeAgentCredential(context.Context, *RevokeAgentCredentialRequest) (*RevokeAgentCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAgentCredential not implemented")
}
func (UnimplementedAgentServiceServer) ExchangeAgentCredential(context.Context, *ExchangeAgentCredentialRequest) (*ExchangeAgentCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeAgentCredential not implemented")
}
func (UnimplementedAgentServiceServer) CreateGrant(context.Context, *CreateGrantRequest) (*CreateGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGrant not implemented")
}
func (UnimplementedAgentServiceServer) ListGrants(context.Context, *ListGrantsRequest) (*ListGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGrants not implemented")
}
func (UnimplementedAgentServiceServer) DeleteGrant(context.Context, *DeleteGrantRequest) (*DeleteGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGrant not implemented")
}
func (UnimplementedAgentServiceServer) SendToAgent(context.Context, *SendToAgentRequest) (*SendToAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToAgent not implemented")
}
func (UnimplementedAgentServiceServer) ReceiveInbox(context.Context, *ReceiveInboxRequest) (*ReceiveInboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveInbox not implemented")
}
func (UnimplementedAgentServiceServer) ListenInbox(*ListenInboxRequest, grpc.ServerStreamingServer[ListenInboxResponse]) error {
	return status.Error(codes.Unimplemented, "method ListenInbox not implemented")
}
func (UnimplementedAgentServiceServer) AckInbox(context.Context, *AckInboxRequest) (*AckInboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckInbox not implemented")
}
func (UnimplementedAgentServiceServer) NackInbox(context.Context, *NackInboxRequest) (*NackInboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NackInbox not implemented")
}
func (UnimplementedAgentServiceServer) ExtendInboxLease(context.Context, *ExtendInboxLeaseRequest) (*ExtendInboxLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendInboxLease not implemented")
}
func (UnimplementedAgentServiceServer) SubscribeAgent(context.Context, *SubscribeAgentRequest) (*SubscribeAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeAgent not implemented")
}
func (UnimplementedAgentServiceServer) UnsubscribeAgent(context.Context, *UnsubscribeAgentRequest) (*UnsubscribeAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeAgent not implemented")
}
func (UnimplementedAgentServiceServer) ListAgentSubscriptions(context.Context, *ListAgentSubscriptionsRequest) (*ListAgentSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentSubscriptions not implemented")
}
func (UnimplementedAgentServiceServer) ListAgentDeadLetters(context.Context, *ListAgentDeadLettersRequest) (*ListAgentDeadLettersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentDeadLetters not implemented")
}
func (UnimplementedAgentServiceServer) ReplayAgentDeadLetter(context.Context, *ReplayAgentDeadLetterRequest) (*ReplayAgentDeadLetterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayAgentDeadLetter not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SetAgentStatus(ctx, req.(*SetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateAgentCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAgentCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateAgentCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAgentCredential(ctx, req.(*CreateAgentCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgentCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgentCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgentCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgentCredentials(ctx, req.(*ListAgentCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RegisterAgentCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterAgentCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterAgentCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterAgentCredential(ctx, req.(*RegisterAgentCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RevokeAgentCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAgentCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RevokeAgentCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RevokeAgentCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RevokeAgentCredential(ctx, req.(*RevokeAgentCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExchangeAgentCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeAgentCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExchangeAgentCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExchangeAgentCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExchangeAgentCredential(ctx, req.(*ExchangeAgentCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateGrant(ctx, req.(*CreateGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListGrants(ctx, req.(*ListGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteGrant(ctx, req.(*DeleteGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SendToAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendToAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SendToAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendToAgent(ctx, req.(*SendToAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReceiveInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveInboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReceiveInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReceiveInbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReceiveInbox(ctx, req.(*ReceiveInboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListenInbox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenInboxRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ListenInbox(m, &grpc.GenericServerStream[ListenInboxRequest, ListenInboxResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ListenInboxServer = grpc.ServerStreamingServer[ListenInboxResponse]

func _AgentService_AckInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckInboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AckInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AckInbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AckInbox(ctx, req.(*AckInboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_NackInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackInboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).NackInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_NackInbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).NackInbox(ctx, req.(*NackInboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExtendInboxLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendInboxLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExtendInboxLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExtendInboxLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExtendInboxLease(ctx, req.(*ExtendInboxLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SubscribeAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SubscribeAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SubscribeAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SubscribeAgent(ctx, req.(*SubscribeAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UnsubscribeAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UnsubscribeAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UnsubscribeAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UnsubscribeAgent(ctx, req.(*UnsubscribeAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgentSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgentSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgentSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgentSubscriptions(ctx, req.(*ListAgentSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgentDeadLetters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentDeadLettersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgentDeadLetters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgentDeadLetters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgentDeadLetters(ctx, req.(*ListAgentDeadLettersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReplayAgentDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayAgentDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReplayAgentDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReplayAgentDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReplayAgentDeadLetter(ctx, req.(*ReplayAgentDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentService_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentService_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentService_ListAgents_Handler,
		},
		{
			MethodName: "SetAgentStatus",
			Handler:    _AgentService_SetAgentStatus_Handler,
		},
		{
			MethodName: "CreateAgentCredential",
			Handler:    _AgentService_CreateAgentCredential_Handler,
		},
		{
			MethodName: "ListAgentCredentials",
			Handler:    _AgentService_ListAgentCredentials_Handler,
		},
		{
			MethodName: "RegisterAgentCredential",
			Handler:    _AgentService_RegisterAgentCredential_Handler,
		},
		{
			MethodName: "RevokeAgentCredential",
			Handler:    _AgentService_RevokeAgentCredential_Handler,
		},
		{
			MethodName: "ExchangeAgentCredential",
			Handler:    _AgentService_ExchangeAgentCredential_Handler,
		},
		{
			MethodName: "CreateGrant",
			Handler:    _AgentService_CreateGrant_Handler,
		},
		{
			MethodName: "ListGrants",
			Handler:    _AgentService_ListGrants_Handler,
		},
		{
			MethodName: "DeleteGrant",
			Handler:    _AgentService_DeleteGrant_Handler,
		},
		{
			MethodName: "SendToAgent",
			Handler:    _AgentService_SendToAgent_Handler,
		},
		{
			MethodName: "ReceiveInbox",
			Handler:    _AgentService_ReceiveInbox_Handler,
		},
		{
			MethodName: "AckInbox",
			Handler:    _AgentService_AckInbox_Handler,
		},
		{
			MethodName: "NackInbox",
			Handler:    _AgentService_NackInbox_Handler,
		},
		{
			MethodName: "ExtendInboxLease",
			Handler:    _AgentService_ExtendInboxLease_Handler,
		},
		{
			MethodName: "SubscribeAgent",
			Handler:    _AgentService_SubscribeAgent_Handler,
		},
		{
			MethodName: "UnsubscribeAgent",
			Handler:    _AgentService_UnsubscribeAgent_Handler,
		},
		{
			MethodName: "ListAgentSubscriptions",
			Handler:    _AgentService_ListAgentSubscriptions_Handler,
		},
		{
			MethodName: "ListAgentDeadLetters",
			Handler:    _AgentService_ListAgentDeadLetters_Handler,
		},
		{
			MethodName: "ReplayAgentDeadLetter",
			Handler:    _AgentService_ReplayAgentDeadLetter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenInbox",
			Handler:       _AgentService_ListenInbox_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/v1/messaging.proto",
}

const (
	PubSubService_CreateTopic_FullMethodName             = "/agent.v1.PubSubService/CreateTopic"
	PubSubService_GetTopic_FullMethodName                = "/agent.v1.PubSubService/GetTopic"
	PubSubService_ListTopics_FullMethodName              = "/agent.v1.PubSubService/ListTopics"
	PubSubService_DeleteTopic_FullMethodName             = "/agent.v1.PubSubService/DeleteTopic"
	PubSubService_Publish_FullMethodName                 = "/agent.v1.PubSubService/Publish"
	PubSubService_CreateSubscription_FullMethodName      = "/agent.v1.PubSubService/CreateSubscription"
	PubSubService_GetSubscription_FullMethodName         = "/agent.v1.PubSubService/GetSubscription"
	PubSubService_ListSubscriptions_FullMethodName       = "/agent.v1.PubSubService/ListSubscriptions"
	PubSubService_DeleteSubscription_FullMethodName      = "/agent.v1.PubSubService/DeleteSubscription"
	PubSubService_SeekSubscription_FullMethodName        = "/agent.v1.PubSubService/SeekSubscription"
	PubSubService_PullSubscription_FullMethodName        = "/agent.v1.PubSubService/PullSubscription"
	PubSubService_ListenSubscription_FullMethodName      = "/agent.v1.PubSubService/ListenSubscription"
	PubSubService_AckSubscription_FullMethodName         = "/agent.v1.PubSubService/AckSubscription"
	PubSubService_NackSubscription_FullMethodName        = "/agent.v1.PubSubService/NackSubscription"
	PubSubService_ExtendSubscriptionLease_FullMethodName = "/agent.v1.PubSubService/ExtendSubscriptionLease"
)

// PubSubServiceClient is the client API for PubSubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PubSubServiceClient interface {
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*GetTopicResponse, error)
	ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*DeleteTopicResponse, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error)
	ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error)
	SeekSubscription(ctx context.Context, in *SeekSubscriptionRequest, opts ...grpc.CallOption) (*SeekSubscriptionResponse, error)
	PullSubscription(ctx context.Context, in *PullSubscriptionRequest, opts ...grpc.CallOption) (*PullSubscriptionResponse, error)
	ListenSubscription(ctx context.Context, in *ListenSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenSubscriptionResponse], error)
	AckSubscription(ctx context.Context, in *AckSubscriptionRequest, opts ...grpc.CallOption) (*AckSubscriptionResponse, error)
	NackSubscription(ctx context.Context, in *NackSubscriptionRequest, opts ...grpc.CallOption) (*NackSubscriptionResponse, error)
	ExtendSubscriptionLease(ctx context.Context, in *ExtendSubscriptionLeaseRequest, opts ...grpc.CallOption) (*ExtendSubscriptionLeaseResponse, error)
}

type pubSubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPubSubServiceClient(cc grpc.ClientConnInterface) PubSubServiceClient {
	return &pubSubServiceClient{cc}
}

func (c *pubSubServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, PubSubService_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*GetTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicResponse)
	err := c.cc.Invoke(ctx, PubSubService_GetTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, PubSubService_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*DeleteTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTopicResponse)
	err := c.cc.Invoke(ctx, PubSubService_DeleteTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, PubSubService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, PubSubService_CreateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscriptionResponse)
	err := c.cc.Invoke(ctx, PubSubService_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubscriptionsResponse)
	err := c.cc.Invoke(ctx, PubSubService_ListSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, PubSubService_DeleteSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) SeekSubscription(ctx context.Context, in *SeekSubscriptionRequest, opts ...grpc.CallOption) (*SeekSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeekSubscriptionResponse)
	err := c.cc.Invoke(ctx, PubSubService_SeekSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) PullSubscription(ctx context.Context, in *PullSubscriptionRequest, opts ...grpc.CallOption) (*PullSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullSubscriptionResponse)
	err := c.cc.Invoke(ctx, PubSubService_PullSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) ListenSubscription(ctx context.Context, in *ListenSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenSubscriptionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PubSubService_ServiceDesc.Streams[0], PubSubService_ListenSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenSubscriptionRequest, ListenSubscriptionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSubService_ListenSubscriptionClient = grpc.ServerStreamingClient[ListenSubscriptionResponse]

func (c *pubSubServiceClient) AckSubscription(ctx context.Context, in *AckSubscriptionRequest, opts ...grpc.CallOption) (*AckSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckSubscriptionResponse)
	err := c.cc.Invoke(ctx, PubSubService_AckSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) NackSubscription(ctx context.Context, in *NackSubscriptionRequest, opts ...grpc.CallOption) (*NackSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NackSubscriptionResponse)
	err := c.cc.Invoke(ctx, PubSubService_NackSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubServiceClient) ExtendSubscriptionLease(ctx context.Context, in *ExtendSubscriptionLeaseRequest, opts ...grpc.CallOption) (*ExtendSubscriptionLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendSubscriptionLeaseResponse)
	err := c.cc.Invoke(ctx, PubSubService_ExtendSubscriptionLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PubSubServiceServer is the server API for PubSubService service.
// All implementations must embed UnimplementedPubSubServiceServer
// for forward compatibility.
type PubSubServiceServer interface {
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	GetTopic(context.Context, *GetTopicRequest) (*GetTopicResponse, error)
	ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error)
	DeleteTopic(context.Context, *DeleteTopicRequest) (*DeleteTopicResponse, error)
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error)
	GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error)
	ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error)
	SeekSubscription(context.Context, *SeekSubscriptionRequest) (*SeekSubscriptionResponse, error)
	PullSubscription(context.Context, *PullSubscriptionRequest) (*PullSubscriptionResponse, error)
	ListenSubscription(*ListenSubscriptionRequest, grpc.ServerStreamingServer[ListenSubscriptionResponse]) error
	AckSubscription(context.Context, *AckSubscriptionRequest) (*AckSubscriptionResponse, error)
	NackSubscription(context.Context, *NackSubscriptionRequest) (*NackSubscriptionResponse, error)
	ExtendSubscriptionLease(context.Context, *ExtendSubscriptionLeaseRequest) (*ExtendSubscriptionLeaseResponse, error)
	mustEmbedUnimplementedPubSubServiceServer()
}

// UnimplementedPubSubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPubSubServiceServer struct{}

func (UnimplementedPubSubServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedPubSubServiceServer) GetTopic(context.Context, *GetTopicRequest) (*GetTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopic not implemented")
}
func (UnimplementedPubSubServiceServer) ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedPubSubServiceServer) DeleteTopic(context.Context, *DeleteTopicRequest) (*DeleteTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTopic not implemented")
}
func (UnimplementedPubSubServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPubSubServiceServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedPubSubServiceServer) GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedPubSubServiceServer) ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (UnimplementedPubSubServiceServer) DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedPubSubServiceServer) SeekSubscription(context.Context, *SeekSubscriptionRequest) (*SeekSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeekSubscription not implemented")
}
func (UnimplementedPubSubServiceServer) PullSubscription(context.Context, *PullSubscriptionRequest) (*PullSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullSubscription not implemented")
}
func (UnimplementedPubSubServiceServer) ListenSubscription(*ListenSubscriptionRequest, grpc.ServerStreamingServer[ListenSubscriptionResponse]) error {
	return status.Error(codes.Unimplemented, "method ListenSubscription not implemented")
}
func (UnimplementedPubSubServiceServer) AckSubscription(context.Context, *AckSubscriptionRequest) (*AckSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckSubscription not implemented")
}
func (UnimplementedPubSubServiceServer) NackSubscription(context.Context, *NackSubscriptionRequest) (*NackSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NackSubscription not implemented")
}
func (UnimplementedPubSubServiceServer) ExtendSubscriptionLease(context.Context, *ExtendSubscriptionLeaseRequest) (*ExtendSubscriptionLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendSubscriptionLease not implemented")
}
func (UnimplementedPubSubServiceServer) mustEmbedUnimplementedPubSubServiceServer() {}
func (UnimplementedPubSubServiceServer) testEmbeddedByValue()                       {}

// UnsafePubSubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubSubServiceServer will
// result in compilation errors.
type UnsafePubSubServiceServer interface {
	mustEmbedUnimplementedPubSubServiceServer()
}

func RegisterPubSubServiceServer(s grpc.ServiceRegistrar, srv PubSubServiceServer) {
	// If the following call panics, it indicates UnimplementedPubSubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PubSubService_ServiceDesc, srv)
}

func _PubSubService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_GetTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).GetTopic(ctx, req.(*GetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).ListTopics(ctx, req.(*ListTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_DeleteTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).DeleteTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_DeleteTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).DeleteTopic(ctx, req.(*DeleteTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).GetSubscription(ctx, req.(*GetSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_ListSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).ListSubscriptions(ctx, req.(*ListSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_SeekSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeekSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).SeekSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_SeekSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).SeekSubscription(ctx, req.(*SeekSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_PullSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).PullSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_PullSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).PullSubscription(ctx, req.(*PullSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_ListenSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenSubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubSubServiceServer).ListenSubscription(m, &grpc.GenericServerStream[ListenSubscriptionRequest, ListenSubscriptionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSubService_ListenSubscriptionServer = grpc.ServerStreamingServer[ListenSubscriptionResponse]

func _PubSubService_AckSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).AckSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_AckSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).AckSubscription(ctx, req.(*AckSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_NackSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).NackSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_NackSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).NackSubscription(ctx, req.(*NackSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSubService_ExtendSubscriptionLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendSubscriptionLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServiceServer).ExtendSubscriptionLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubService_ExtendSubscriptionLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServiceServer).ExtendSubscriptionLease(ctx, req.(*ExtendSubscriptionLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PubSubService_ServiceDesc is the grpc.ServiceDesc for PubSubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubSubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.PubSubService",
	HandlerType: (*PubSubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _PubSubService_CreateTopic_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _PubSubService_GetTopic_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _PubSubService_ListTopics_Handler,
		},
		{
			MethodName: "DeleteTopic",
			Handler:    _PubSubService_DeleteTopic_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _PubSubService_Publish_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _PubSubService_CreateSubscription_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _PubSubService_GetSubscription_Handler,
		},
		{
			MethodName: "ListSubscriptions",
			Handler:    _PubSubService_ListSubscriptions_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _PubSubService_DeleteSubscription_Handler,
		},
		{
			MethodName: "SeekSubscription",
			Handler:    _PubSubService_SeekSubscription_Handler,
		},
		{
			MethodName: "PullSubscription",
			Handler:    _PubSubService_PullSubscription_Handler,
		},
		{
			MethodName: "AckSubscription",
			Handler:    _PubSubService_AckSubscription_Handler,
		},
		{
			MethodName: "NackSubscription",
			Handler:    _PubSubService_NackSubscription_Handler,
		},
		{
			MethodName: "ExtendSubscriptionLease",
			Handler:    _PubSubService_ExtendSubscriptionLease_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenSubscription",
			Handler:       _PubSubService_ListenSubscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/v1/messaging.proto",
}

const (
	SystemService_GetCapabilities_FullMethodName = "/agent.v1.SystemService/GetCapabilities"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemServiceClient interface {
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, SystemService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
type SystemServiceServer interface {
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _SystemService_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/messaging.proto",
}
