// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id, created_at)
VALUES ($1, $2, $3)
`

type AssignUserRoleParams struct {
	UserID    string
	RoleID    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleID, arg.CreatedAt)
	return err
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*)
FROM user_roles ur
         INNER JOIN roles r ON ur.role_id = r.role_id
WHERE r.role_name = 'admin'
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (
    id, aid, token_hash, created_at_ns, expires_at_ns, last_used_at_ns
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRefreshTokenParams struct {
	ID           string
	Aid          string
	TokenHash    []byte
	CreatedAtNs  int64
	ExpiresAtNs  int64
	LastUsedAtNs int64
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.Aid,
		arg.TokenHash,
		arg.CreatedAtNs,
		arg.ExpiresAtNs,
		arg.LastUsedAtNs,
	)
	return err
}

const createSecurityAuditEvent = `-- name: CreateSecurityAuditEvent :exec
INSERT INTO security_audit_events (
    audit_id, tenant_id, principal_kind, principal_id, action,
    resource_kind, resource_id, outcome, request_id, reason, source_ip,
    user_agent, metadata_json, created_at_ns
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateSecurityAuditEventParams struct {
	AuditID       string
	TenantID      string
	PrincipalKind string
	PrincipalID   string
	Action        string
	ResourceKind  string
	ResourceID    string
	Outcome       string
	RequestID     string
	Reason        string
	SourceIp      string
	UserAgent     string
	MetadataJson  []byte
	CreatedAtNs   int64
}

func (q *Queries) CreateSecurityAuditEvent(ctx context.Context, arg CreateSecurityAuditEventParams) error {
	_, err := q.db.Exec(ctx, createSecurityAuditEvent,
		arg.AuditID,
		arg.TenantID,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.Action,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Outcome,
		arg.RequestID,
		arg.Reason,
		arg.SourceIp,
		arg.UserAgent,
		arg.MetadataJson,
		arg.CreatedAtNs,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    user_id, email, password, verified, created_at, updated_at,
    org_id, auth_version, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	UserID      string
	Email       string
	Password    string
	Verified    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	OrgID       string
	AuthVersion int64
	Status      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Password,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.OrgID,
		arg.AuthVersion,
		arg.Status,
	)
	return err
}

const getAdminRoleID = `-- name: GetAdminRoleID :one
SELECT role_id
FROM roles
WHERE role_name = 'admin'
`

func (q *Queries) GetAdminRoleID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getAdminRoleID)
	var role_id string
	err := row.Scan(&role_id)
	return role_id, err
}

const upsertHumanSecurityPrincipal = `-- name: UpsertHumanSecurityPrincipal :exec
INSERT INTO security_principals (
    tenant_id, principal_kind, principal_id, status, roles_json,
    auth_version, updated_at_ns
)
SELECT u.org_id,
       'human',
       u.user_id,
       u.status,
       COALESCE((
           SELECT jsonb_agg(role_name ORDER BY role_name)
           FROM (
               SELECT r.role_name AS role_name
               FROM user_roles ur
               JOIN roles r ON r.role_id = ur.role_id
               WHERE ur.user_id = u.user_id
           ) roles
       ), '[]'::jsonb),
       u.auth_version,
       $1
FROM users u
WHERE u.user_id = $2
ON CONFLICT(tenant_id, principal_kind, principal_id) DO UPDATE SET
    status = excluded.status,
    roles_json = excluded.roles_json,
    auth_version = excluded.auth_version,
    updated_at_ns = excluded.updated_at_ns
`

type UpsertHumanSecurityPrincipalParams struct {
	UpdatedAtNs int64
	UserID      string
}

func (q *Queries) UpsertHumanSecurityPrincipal(ctx context.Context, arg UpsertHumanSecurityPrincipalParams) error {
	_, err := q.db.Exec(ctx, upsertHumanSecurityPrincipal, arg.UpdatedAtNs, arg.UserID)
	return err
}
