// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDirectoryAccounts = `-- name: CountDirectoryAccounts :one
SELECT count(*)
FROM users u
WHERE ($1::text = '' OR lower(u.email) LIKE '%' || lower($1::text) || '%')
  AND (NOT $2::boolean OR coalesce(u.org_id, '') = $3::text)
`

type CountDirectoryAccountsParams struct {
	Search   string
	ScopeOrg bool
	OrgID    string
}

func (q *Queries) CountDirectoryAccounts(ctx context.Context, arg CountDirectoryAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDirectoryAccounts, arg.Search, arg.ScopeOrg, arg.OrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO users (user_id, email, password, verified, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAccountParams struct {
	UserID    string
	Email     string
	Password  string
	Verified  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.UserID,
		arg.Email,
		arg.Password,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, aid, token, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID        string
	Aid       string
	Token     string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.Aid,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :execrows
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshTokenByTokenID = `-- name: DeleteRefreshTokenByTokenID :exec
DELETE FROM refresh_tokens
WHERE id = $1
`

func (q *Queries) DeleteRefreshTokenByTokenID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByTokenID, id)
	return err
}

const denyAccessToken = `-- name: DenyAccessToken :exec
INSERT INTO denylist (token, denied_until)
VALUES ($1, $2)
`

type DenyAccessTokenParams struct {
	Token       string
	DeniedUntil int64
}

func (q *Queries) DenyAccessToken(ctx context.Context, arg DenyAccessTokenParams) error {
	_, err := q.db.Exec(ctx, denyAccessToken, arg.Token, arg.DeniedUntil)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT user_id, email, password, verified, created_at, updated_at
FROM users
WHERE email = $1
`

type GetAccountByEmailRow struct {
	UserID    string
	Email     string
	Password  string
	Verified  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT user_id, email, password, verified, created_at, updated_at
FROM users
WHERE user_id = $1
`

type GetAccountByIDRow struct {
	UserID    string
	Email     string
	Password  string
	Verified  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetAccountByID(ctx context.Context, userID string) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, userID)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountOrgID = `-- name: GetAccountOrgID :one
SELECT coalesce(org_id, '')::text AS org_id
FROM users
WHERE user_id = $1
`

func (q *Queries) GetAccountOrgID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getAccountOrgID, userID)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.role_name
FROM roles r
         INNER JOIN user_roles ur ON r.role_id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.role_name
`

func (q *Queries) GetUserRoles(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_name string
		if err := rows.Scan(&role_name); err != nil {
			return nil, err
		}
		items = append(items, role_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isAccessTokenDenied = `-- name: IsAccessTokenDenied :one
SELECT count(*)
FROM denylist
WHERE token = $1
  AND denied_until > $2
`

type IsAccessTokenDeniedParams struct {
	Token       string
	DeniedUntil int64
}

func (q *Queries) IsAccessTokenDenied(ctx context.Context, arg IsAccessTokenDeniedParams) (int64, error) {
	row := q.db.QueryRow(ctx, isAccessTokenDenied, arg.Token, arg.DeniedUntil)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDirectoryAccounts = `-- name: ListDirectoryAccounts :many
SELECT u.user_id,
       u.email,
       u.verified,
       u.created_at,
       u.updated_at,
       u.org_id,
       u.oauth_provider,
       u.is_oauth_user,
       u.last_sync_at,
       o.org_code,
       o.org_name
FROM users u
         LEFT JOIN organizations o ON o.org_id = u.org_id
WHERE ($1::text = '' OR lower(u.email) LIKE '%' || lower($1::text) || '%')
  AND (NOT $2::boolean OR coalesce(u.org_id, '') = $3::text)
  AND ($4::text = '' OR u.user_id > $4::text)
ORDER BY u.user_id
LIMIT $5::bigint
`

type ListDirectoryAccountsParams struct {
	Search    string
	ScopeOrg  bool
	OrgID     string
	Cursor    string
	PageLimit int64
}

type ListDirectoryAccountsRow struct {
	UserID        string
	Email         string
	Verified      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OrgID         pgtype.Text
	OauthProvider pgtype.Text
	IsOauthUser   bool
	LastSyncAt    pgtype.Timestamptz
	OrgCode       pgtype.Text
	OrgName       pgtype.Text
}

func (q *Queries) ListDirectoryAccounts(ctx context.Context, arg ListDirectoryAccountsParams) ([]ListDirectoryAccountsRow, error) {
	rows, err := q.db.Query(ctx, listDirectoryAccounts,
		arg.Search,
		arg.ScopeOrg,
		arg.OrgID,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectoryAccountsRow{}
	for rows.Next() {
		var i ListDirectoryAccountsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.OauthProvider,
			&i.IsOauthUser,
			&i.LastSyncAt,
			&i.OrgCode,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForAccounts = `-- name: ListRolesForAccounts :many
SELECT ur.user_id, r.role_id, r.role_name
FROM user_roles ur
         INNER JOIN roles r ON r.role_id = ur.role_id
WHERE ur.user_id = ANY ($1::text[])
ORDER BY ur.user_id, r.role_name
`

type ListRolesForAccountsRow struct {
	UserID   string
	RoleID   string
	RoleName string
}

func (q *Queries) ListRolesForAccounts(ctx context.Context, userIds []string) ([]ListRolesForAccountsRow, error) {
	rows, err := q.db.Query(ctx, listRolesForAccounts, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesForAccountsRow{}
	for rows.Next() {
		var i ListRolesForAccountsRow
		if err := rows.Scan(&i.UserID, &i.RoleID, &i.RoleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForAccounts = `-- name: ListTeamsForAccounts :many
SELECT ut.user_id, t.team_id, t.org_id, t.team_name, t.team_code
FROM user_teams ut
         INNER JOIN teams t ON t.team_id = ut.team_id
WHERE ut.user_id = ANY ($1::text[])
ORDER BY ut.user_id, t.team_name
`

type ListTeamsForAccountsRow struct {
	UserID   string
	TeamID   string
	OrgID    string
	TeamName string
	TeamCode string
}

func (q *Queries) ListTeamsForAccounts(ctx context.Context, userIds []string) ([]ListTeamsForAccountsRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForAccounts, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForAccountsRow{}
	for rows.Next() {
		var i ListTeamsForAccountsRow
		if err := rows.Scan(
			&i.UserID,
			&i.TeamID,
			&i.OrgID,
			&i.TeamName,
			&i.TeamCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeRefreshTokens = `-- name: PurgeRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE aid = $1
`

func (q *Queries) PurgeRefreshTokens(ctx context.Context, aid string) error {
	_, err := q.db.Exec(ctx, purgeRefreshTokens, aid)
	return err
}

const setAccountPassword = `-- name: SetAccountPassword :execrows
UPDATE users
SET password   = $1,
    updated_at = now()
WHERE user_id = $2
`

type SetAccountPasswordParams struct {
	Password string
	UserID   string
}

func (q *Queries) SetAccountPassword(ctx context.Context, arg SetAccountPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountPassword, arg.Password, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountVerified = `-- name: SetAccountVerified :execrows
UPDATE users
SET verified   = $1,
    updated_at = now()
WHERE email = $2
`

type SetAccountVerifiedParams struct {
	Verified bool
	Email    string
}

func (q *Queries) SetAccountVerified(ctx context.Context, arg SetAccountVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountVerified, arg.Verified, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
