{{- if and .Values.cluster.enabled (not .Values.cluster.existingSecret) -}}
{{- if or .Values.cluster.gossipSecret .Values.cluster.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cluster" (include "plainq.fullname" .) }}
  labels:
    {{- include "plainq.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.cluster.gossipSecret }}
  {{ .Values.cluster.gossipSecretKey }}: {{ .Values.cluster.gossipSecret | quote }}
  {{- end }}
  {{- if .Values.cluster.secret }}
  {{ .Values.cluster.secretKey }}: {{ .Values.cluster.secret | quote }}
  {{- end }}
{{- end }}
{{- end }}
