// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO users (user_id, email, password, verified, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	UserID    string
	Email     string
	Password  string
	Verified  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.UserID,
		arg.Email,
		arg.Password,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, aid, token, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateRefreshTokenParams struct {
	ID        string
	Aid       string
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.Aid,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM users
WHERE user_id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccount, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token = ?
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, token)
	return err
}

const deleteRefreshTokenByTokenID = `-- name: DeleteRefreshTokenByTokenID :exec
DELETE FROM refresh_tokens
WHERE id = ?
`

func (q *Queries) DeleteRefreshTokenByTokenID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenByTokenID, id)
	return err
}

const denyAccessToken = `-- name: DenyAccessToken :exec
INSERT INTO denylist (token, denied_until)
VALUES (?, ?)
`

type DenyAccessTokenParams struct {
	Token       string
	DeniedUntil int64
}

func (q *Queries) DenyAccessToken(ctx context.Context, arg DenyAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, denyAccessToken, arg.Token, arg.DeniedUntil)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT user_id, email, password, verified, created_at, updated_at
FROM users
WHERE email = ?
`

type GetAccountByEmailRow struct {
	UserID    string
	Email     string
	Password  string
	Verified  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT user_id, email, password, verified, created_at, updated_at
FROM users
WHERE user_id = ?
`

type GetAccountByIDRow struct {
	UserID    string
	Email     string
	Password  string
	Verified  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetAccountByID(ctx context.Context, userID string) (GetAccountByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, userID)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.role_name
FROM roles r
         INNER JOIN user_roles ur ON r.role_id = ur.role_id
WHERE ur.user_id = ?
ORDER BY r.role_name
`

func (q *Queries) GetUserRoles(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_name string
		if err := rows.Scan(&role_name); err != nil {
			return nil, err
		}
		items = append(items, role_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeRefreshTokens = `-- name: PurgeRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE aid = ?
`

func (q *Queries) PurgeRefreshTokens(ctx context.Context, aid string) error {
	_, err := q.db.ExecContext(ctx, purgeRefreshTokens, aid)
	return err
}

const setAccountPassword = `-- name: SetAccountPassword :execrows
UPDATE users
SET password   = ?,
    updated_at = current_timestamp
WHERE user_id = ?
`

type SetAccountPasswordParams struct {
	Password string
	UserID   string
}

func (q *Queries) SetAccountPassword(ctx context.Context, arg SetAccountPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountPassword, arg.Password, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountVerified = `-- name: SetAccountVerified :execrows
UPDATE users
SET verified   = ?,
    updated_at = current_timestamp
WHERE email = ?
`

type SetAccountVerifiedParams struct {
	Verified bool
	Email    string
}

func (q *Queries) SetAccountVerified(ctx context.Context, arg SetAccountVerifiedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountVerified, arg.Verified, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
