// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Denylist struct {
	Token       string
	DeniedUntil int64
}

type OauthProvider struct {
	ProviderID   string
	ProviderName string
	OrgID        sql.NullString
	ConfigJson   string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Organization struct {
	OrgID     string
	OrgCode   string
	OrgName   string
	OrgDomain sql.NullString
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type QueuePermission struct {
	QueueID    string
	RoleID     string
	CanSend    bool
	CanReceive bool
	CanPurge   bool
	CanDelete  bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type QueueProperty struct {
	QueueID                  string
	QueueName                string
	CreatedAt                time.Time
	GcAt                     time.Time
	RetentionPeriodSeconds   int64
	VisibilityTimeoutSeconds int64
	MaxReceiveAttempts       int64
	DropPolicy               int64
	DeadLetterQueueID        sql.NullString
}

type RefreshToken struct {
	ID        string
	Aid       string
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Role struct {
	RoleID    string
	RoleName  string
	CreatedAt time.Time
}

type Team struct {
	TeamID      string
	OrgID       string
	TeamName    string
	TeamCode    string
	Description sql.NullString
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TeamRole struct {
	TeamID    string
	RoleID    string
	CreatedAt time.Time
}

type User struct {
	UserID        string
	Email         string
	Password      string
	Verified      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	OrgID         sql.NullString
	OauthProvider sql.NullString
	OauthSub      sql.NullString
	LastSyncAt    sql.NullTime
	IsOauthUser   bool
}

type UserRole struct {
	UserID    string
	RoleID    string
	CreatedAt time.Time
}

type UserTeam struct {
	UserID    string
	TeamID    string
	CreatedAt time.Time
}
