name: Merge to Main

on:
  push:
    paths-ignore:
      - internal/houston/ui
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: internal/houston/ui/package-lock.json
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.26'

      - name: build houston ui
        working-directory: internal/houston/ui
        run: npm ci && npm run build

      - name: go tests
        run: go test -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: internal/houston/ui/package-lock.json
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.26'

      - name: build houston ui
        working-directory: internal/houston/ui
        run: npm ci && npm run build

      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=3m
