name: Merge to Main

on:
  push:
    paths-ignore:
      - internal/houston/ui
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.13
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.26'

      - name: build houston ui
        run: make houston

      - name: go tests
        run: go test -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.13
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.26'

      - name: build houston ui
        run: make houston

      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=3m
