// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO security_audit_events (
    audit_id, tenant_id, principal_kind, principal_id, action,
    resource_kind, resource_id, outcome, request_id, reason,
    source_ip, user_agent, metadata_json, created_at_ns
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertAuditEventParams struct {
	AuditID       string
	TenantID      string
	PrincipalKind string
	PrincipalID   string
	Action        string
	ResourceKind  string
	ResourceID    string
	Outcome       string
	RequestID     string
	Reason        string
	SourceIp      string
	UserAgent     string
	MetadataJson  []byte
	CreatedAtNs   int64
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.AuditID,
		arg.TenantID,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.Action,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Outcome,
		arg.RequestID,
		arg.Reason,
		arg.SourceIp,
		arg.UserAgent,
		arg.MetadataJson,
		arg.CreatedAtNs,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT audit_id, tenant_id, principal_kind, principal_id, action,
       resource_kind, resource_id, outcome, request_id, reason,
       source_ip, user_agent, metadata_json, created_at_ns
FROM security_audit_events
WHERE tenant_id = $1::text
  AND ($2::text = '' OR action = $2::text)
  AND ($3::text = '' OR resource_kind = $3::text)
  AND ($4::text = '' OR resource_id = $4::text)
  AND ($5::bigint = 0
       OR created_at_ns > $5::bigint
       OR (created_at_ns = $5::bigint AND audit_id > $6::text))
ORDER BY created_at_ns, audit_id
LIMIT $7::bigint
`

type ListAuditEventsParams struct {
	TenantID     string
	Action       string
	ResourceKind string
	ResourceID   string
	AfterTimeNs  int64
	AfterID      string
	PageLimit    int64
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]SecurityAuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.TenantID,
		arg.Action,
		arg.ResourceKind,
		arg.ResourceID,
		arg.AfterTimeNs,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityAuditEvent{}
	for rows.Next() {
		var i SecurityAuditEvent
		if err := rows.Scan(
			&i.AuditID,
			&i.TenantID,
			&i.PrincipalKind,
			&i.PrincipalID,
			&i.Action,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Outcome,
			&i.RequestID,
			&i.Reason,
			&i.SourceIp,
			&i.UserAgent,
			&i.MetadataJson,
			&i.CreatedAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
