// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type SecurityAuditEvent struct {
	AuditID       string
	TenantID      string
	PrincipalKind string
	PrincipalID   string
	Action        string
	ResourceKind  string
	ResourceID    string
	Outcome       string
	RequestID     string
	Reason        string
	SourceIp      string
	UserAgent     string
	MetadataJson  []byte
	CreatedAtNs   int64
}
